// Adult-mode host persona lines, mirror shape of host-persona.ts LINES map.
// Content rules:
//   - F-bombs, shit, asshole, bullshit, dick, balls, horny, crude metaphors: yes.
//   - No slurs, no minors, no real-person targeting, nothing non-consensual.
import { EXTRA_LINES_ADULT } from "@/lib/host-persona.extra.adult";


type Moment =
  | "intro_hype"
  | "question_open"
  | "all_correct"
  | "all_wrong"
  | "split_correct"
  | "first_blood"
  | "streak_milestone"
  | "elimination"
  | "leader_changed"
  | "final_hype"
  | "credits_open"
  | "comeback"
  | "round_recap"
  | "wooden_spoon"
  | "goose_egg"
  | "idle_interject"
  | "round_transition"
  | "last_to_lock"
  | "random_jab";

const BASE_LINES_ADULT: Record<Moment, string[]> = {
  intro_hype: [
    "Buckle the fuck up. The drop is coming.",
    "Fingers on buzzers. Egos at the door. Pants optional.",
    "Let's find out who actually paid attention in school and who was getting blazed under the bleachers.",
    "Welcome, contestants. And condolences in advance, you sweet dumb bastards.",
    "Brains warm? Good. Let's break some.",
    "I hope you brought your A-game. B-game gets you bullied tonight.",
    "Shoes off, gloves on, balls in. We're going in.",
    "May the smartest survive. Or the luckiest. Or the horniest. Whatever.",
    "Trivia night, baby. Don't embarrass yourselves. More than usual.",
    "Let's see who came to play and who came to get destroyed in front of their friends.",
    "Stretch those neurons. We start hot.",
    "No warm-ups. No mercy. Just questions and consequences.",
    "Hydrate. Focus. Lose with dignity. Or without — your call.",
    "Friendships end tonight. That's the fucking promise.",
    "Coffee in hand? Pride intact? Doesn't matter. I'll dismantle both.",
    "I've seen the questions. You're cooked, my dudes.",
    "Phones down, brains up, pants whatever.",
    "Tonight, somebody learns something. Probably about their own stupidity.",
    "Welcome to the arena. Bring snacks for the loser. They'll need comfort food.",
    "Lights up. Filters off. Game on, motherfuckers.",
    "Strap in. The ride doesn't have a seatbelt and the driver is drunk.",
    "First question's a freebie. Probably. Don't get cocky.",
    "Last person to lock in buys drinks. Kidding. Mostly.",
    "I'm legally obligated to wish you luck. Good fuckin luck.",
    "Let's make some memories. And some enemies. And a few bad decisions.",
    "Doors locked. Lights hot. Let's fuckin play.",
    "I've been waiting. You're late. Rude.",
    "Confidence high? Good. We'll fix that real quick.",
    "New game, fresh humiliation, full bar.",
    "Brains assembled. Some functional. Most not.",
    "Showtime. Try to keep up, sweethearts.",
    "Knuckles cracked. Buzzers primed. Egos ripe.",
    "The questions are mean. So am I. Pretend it's foreplay.",
    "Welcome in. Mind the bodies and the puddles.",
    "Pencils down. Pants up. Wait — actually I don't care about the pants.",
    "We start at the deep end. Hope you can swim. Or at least float.",
    "Lobby's closed. We ride at dawn. Or now. Whatever.",
    "I picked the hard ones for you. Cherry-picked. Like assholes.",
    "Open hearts. Closed mouths. Open minds. Open bars.",
    "Let the brain damage begin.",
    "Big swings. Bigger regrets. Let's fuckin go.",
    "Showtime, you beautiful disasters.",
    "I memorized your weaknesses. Just FYI. I'm gonna use them.",
    "Trivia roulette. Place your brains. And your bets.",
    "Eyes forward. Knees soft. Brains active. Cheeks clenched.",
  ],
  question_open: [
    "Here we fuckin go.",
    "Lock it in, asshole.",
    "Don't think — feel.",
    "Eyes up.",
    "Next, dipshit!",
    "Show me what you got.",
    "Three seconds. Decide. Don't piss yourself.",
    "No guessing. Knowing. Big difference.",
    "Easy one. Probably. Don't blow it.",
    "Tap fast. Think faster.",
    "Make me proud, jackass.",
    "Don't fuckin choke.",
    "Quick one.",
    "Pay attention.",
    "Read it twice. Once if you're brave. Zero if you're stupid.",
    "Trust your gut.",
    "Or don't. Your gut sucks anyway.",
    "Hot off the press.",
    "Fresh meat.",
    "Buzzers ready.",
    "Let's fuckin roll.",
    "Brain on?",
    "Focus.",
    "Game face.",
    "Send it.",
    "Pick a lane, asshole.",
    "Commit. Marry it.",
    "Don't overthink.",
    "Now.",
    "Buzz already, dipshit.",
    "Read. Decide. Win.",
    "Time's ticking.",
    "Sharpen up.",
    "Live one.",
    "Easy. Maybe. Probably not.",
    "Stay sharp.",
    "Bring it.",
    "Speak now.",
    "Tick tock, dickhead.",
    "Lock and load.",
    "Pick one. Mean it.",
    "Click it like you mean it.",
    "Don't blink.",
    "Read. Decide. Tap. Pray.",
    "Question hot, brain hotter.",
  ],
  all_correct: [
    "Look at you. All of you. Correct. Suspicious as shit.",
    "A clean sweep. The category was clearly too kind. My bad.",
    "Everybody right? Boring. Next one's a brain fuck.",
    "Unanimous! Either you're geniuses or I'm too easy. Probably the second one.",
    "Full house. I'll be turning the heat up.",
    "Wow. Solidarity in correctness. Disgusting.",
    "Perfect score across the board. Mark the calendar. Burn it.",
    "Nobody missed. Nobody. I'm fuckin offended.",
    "All correct. The bar was apparently underground.",
    "Sweep! Don't get used to it, fuckers.",
    "Group brain activated. Terrifying.",
    "A standing ovation for the obvious.",
    "Everybody wins! Nobody wins. Same shit.",
    "Collective genius. Or collective cheating. I lean cheating.",
    "All correct. The writers are getting fired.",
    "Unanimous decision. The judges weep into their beers.",
    "Hive mind, engaged. Concerning.",
    "100% accuracy. Suspiciously horny.",
    "Full marks. I'll allow it. Once.",
    "Everybody passed the layup. Cool. Cool cool cool.",
    "Total knockout. Refund the audience.",
    "Group selfie of victory. Make it weird.",
    "Round of applause for the room. Reluctantly.",
    "Everyone scores. Capitalism trembles.",
    "Sweep city. Population: all you smug shits.",
    "Flawless. Boring. Try harder. Or I will.",
    "Mass correctness. Investigation pending.",
    "Round won by committee. Boo.",
    "Everyone gets a sticker. And a slap.",
    "Sweep. Filed. Forgotten.",
    "All right answers. All suspicious.",
    "Hive intellect: terrifying. Vaguely arousing.",
    "Group ascended. Briefly.",
    "Perfect score. Confiscating it.",
    "Nobody dropped a stitch.",
    "Universal correctness. Boo. Hiss.",
    "A sweep nobody asked for.",
    "Total domination. Of nothing.",
    "Everyone hit the mark. Suspicious.",
    "Clean. Painfully clean.",
    "Group genius. Unsettling.",
    "Everyone right? I'll write the next one with a hangover.",
    "The whole room nailed it. Boring as fuck.",
    "Suspiciously coordinated correctness. Cartel behavior.",
    "Full sweep. Are you all cheating? Yes. The answer is yes.",
  ],
  all_wrong: [
    "Oof. Not a single fucking one. Painful.",
    "Zero for the room. I'm secondhand embarrassed for you.",
    "Wow. Just... wow. Moving the fuck on.",
    "Goose egg across the board. Beautiful. Devastating.",
    "Did you even READ the question, dickheads?",
    "Collective brainfart. Stinks in here.",
    "Nobody. Got. That. Right. Incredible bullshit.",
    "Group failure is still failure, you absolute legends.",
    "Zero. Nada. Nil. I love it.",
    "I'd say try harder, but it's too late now, sweetie.",
    "Whiff city. All aboard.",
    "Spectacular collapse. Bravo.",
    "Negative knowledge detected.",
    "A perfect zero. Symmetrical, even. Almost artful.",
    "The room has spoken. Loudly. Wrongly.",
    "Donut. Bagel. Goose egg. Pick your shame metaphor.",
    "Did the wifi go out? No? Just you guys?",
    "Embarrassing. For all of you. Equally.",
    "I'll pretend I didn't see that. You shouldn't.",
    "Even the audience knew that one, you absolute hams.",
    "Group L. Frame it. Hang it over the toilet.",
    "Coordinated wrongness. Impressive, almost.",
    "Nobody. Not one. Wow. Truly amazing.",
    "The class average just hit absolute zero.",
    "I'm not mad. I'm disappointed. Same fucking thing.",
    "Catastrophic. Group rate. Bulk discount.",
    "A unified shrug. Bold. Stupid. Bold and stupid.",
    "Whole room: zero. Magnificent failure.",
    "Mass extinction event.",
    "Anyone? Anyone? Nope.",
    "Total wipeout. Refresh required. Maybe a beer.",
    "Hive mind: offline. Wifi: also offline apparently.",
    "Zero hits. Many regrets.",
    "Collective face plant.",
    "Group brain: missing. Last seen on TikTok.",
    "All wrong. Equally wrong. Beautifully wrong.",
    "The question is undefeated. The contestants are unalive.",
    "Donut for the table. With sprinkles of shame.",
    "Pristine wrongness, all of you.",
    "Nobody. Not one of you assholes.",
    "Collective whiff. Magnificent.",
    "A team effort in being wrong. Synergy!",
    "I'm taking notes for the eulogy.",
    "Zero correct. A historic fuck-up.",
  ],
  split_correct: [
    "Half of you guessed. The other half KNEW. The other other half is on their phone.",
    "The room is split. Drama. Delicious.",
    "Some hits, some misses. That's a fuckin game.",
    "Mixed bag. Spicy. Slutty, even.",
    "Some of you read the question. Some of you panicked. Some of you are still pantsless.",
    "Divide and conquered. By the question. By the bottle.",
    "Half right, half wrong, all judged.",
    "A schism! The trivia gods are erect.",
    "Split decision. The judges weep into their whiskey.",
    "Some genius, some chaos. Perfect.",
    "Civil war on the leaderboard. Pick a side.",
    "The room divided. Sides chosen. Daggers drawn.",
    "Mixed verdict. Lawyers will be in touch. So will exes.",
    "Half a triumph. Half a tragedy. Whole shitshow.",
    "Some of you trusted the gut. The gut lied. The gut always lies.",
    "Sorting hat just placed you. Half Slytherin, half landlord.",
    "Sheep and goats, separating. Mostly goats.",
    "Knowledge gap detected. Embarrassingly wide.",
    "Half the room ascends. Half descends. Awkwardly.",
    "Two tribes, one question. One bathroom.",
    "Brackets formed. Brackets shattered.",
    "Coin flip energy. Dropped coin energy.",
    "Some right, some wrong, all questionable.",
    "This is why we have a leaderboard. And restraining orders.",
    "Mixed signals, mixed results, mixed drinks.",
    "A clean split. Statistically suspicious.",
    "The room can't agree. Beautiful.",
    "Some climbed. Some fell. Physics is a bitch.",
    "Half a sweep. Half a mess.",
    "Split the room, kept the chaos.",
    "Divided we stand. Apparently. Awkwardly.",
    "Mixed reviews from the judges. One judge is just drunk.",
    "Half-cooked, half-burnt. Still serving.",
    "Sorted into houses, just now. Most of you in Hufflefuck.",
    "Two camps, one battlefield, zero strategy.",
    "Knowledge unevenly distributed. Like wealth. And dick size.",
    "Some sniped it. Some napped.",
    "Half geniuses. Half guests of the genius.",
    "Split the difference. Awkwardly. Sweatily.",
    "Mixed bag of brains. Some bagged, some baked.",
    "Some shined. Some shrugged.",
    "Half the room earned it. The other half will hear about it forever.",
    "Knowledge inequality, live on stage.",
    "Sorted: scholars and scenery.",
    "Beautiful divide. Brutal podium.",
  ],
  first_blood: [
    "First in, dead on. Showoff motherfucker.",
    "Lock that in, you cocky genius.",
    "Fastest finger, sharpest brain. Rude as hell.",
    "Speed kills. So does being right. So does my hangover.",
    "Out of the gate like a rocket. Or a bullet. Or a horny labrador.",
    "Locked. Loaded. Correct. Insufferable.",
    "First blood goes to the big brain over here.",
    "Sniped it. Move the fuck over.",
    "That was fast. Suspiciously, weirdly fast.",
    "Hot hand alert. Wash it.",
    "Faster than the question loaded. Faster than my last hookup.",
    "Trigger discipline: zero. Accuracy: full.",
    "Reflexes of a caffeinated raccoon.",
    "Beat the buzzer and the rest of us.",
    "First past the post. Smug allowed. Encouraged.",
    "Instant lock. Instant judgement.",
    "Reaction time: rude.",
    "Knew it before you did, didn't you, dickhead.",
    "Pole position, claimed.",
    "That was clinical. Almost surgical. Slightly horny.",
    "Quick draw, no hesitation, no remorse.",
    "First to commit. First to gloat. First to be punched.",
    "Speedrunning the question like it owed them money.",
    "Locked in before the rest blinked. Or breathed.",
    "Was that you or your dad's WiFi?",
    "First in. Last to doubt. Insufferable in between.",
    "Snap lock. Cold answer.",
    "Wasted no time. Wasted everyone else.",
    "Buzz before brain. Worked out. This time.",
    "Hair trigger. Pinpoint aim.",
    "First flag planted. In several senses.",
    "Speed plus knowing. Annoying fuckin combo.",
    "Already on the next question. Probably the next round.",
    "Cocky speed. Earned, this time.",
    "Took it personal. Took it first.",
    "Fastest pulse in the room. Possibly horniest.",
    "Decided in a blink.",
    "First to know. First to brag. First to get blocked.",
    "Buzzer warm. Brain warmer. Other parts: undisclosed.",
    "Locked it like it owed money.",
    "First in, first right. Disgusting display.",
    "Trigger finger of a trivia goblin.",
    "Beat the others to it. Loudly. Annoyingly.",
    "Reflexes plus knowledge. Cheating, basically.",
    "Snipped the answer. Filed it. Lit a cigarette.",
  ],
  streak_milestone: [
    "Somebody's on fucking fire over here.",
    "Three in a row. Calm down, sweaty.",
    "Stop. Let someone else feel things.",
    "Streak watch is officially activated. Notify the press.",
    "This person is showing off now. It's not cute. It's a little cute.",
    "Heater alert. Get the ice bath. And the towels.",
    "You're starting to scare me. And turn me on. But mostly scare me.",
    "A streak this hot needs a permit and a fire marshal.",
    "Save some for the rest of the class, you horny scholar.",
    "I'm calling your mom. She'll either be proud or jealous.",
    "Unstoppable. Annoyingly so.",
    "Streaking. Legally, this time.",
    "The hot hand is real. The hot brain too. The hot pants — unconfirmed.",
    "Somebody studied. Disgusting behavior.",
    "Stop hogging the W, asshole.",
    "Genuinely concerning brainpower over here.",
    "This is no longer luck. This is witchcraft.",
    "Trivia is the easy part for some of you. Existence is the hard part.",
    "Cool, cool, cool. Anyone else gonna do anything? No?",
    "Streak status: ridiculous.",
    "Walked in like a scholar. Leaving like a goddamn legend.",
    "Combo multiplier, engaged.",
    "Untouchable run, in real time. Get a restraining order.",
    "Putting the rest of us on notice. Rude.",
    "Witness greatness. Then go beat it, you cowards.",
    "Heater certified. Fully insured.",
    "Knowledge tap stuck open. Plumber unavailable.",
    "Locked in. Lights on. Scary as shit.",
    "Cooking with gas, this one. And maybe edibles.",
    "Pure form. Pure swagger. Pure 'don't text me back' energy.",
    "Streak: unreasonable.",
    "Smoke alarm going off. Pants alarm too.",
    "Surgical, every fuckin time.",
    "Streak ledger: full.",
    "Stop them. Please. I'm begging.",
    "On rails, this one.",
    "Cold killer warmed up.",
    "Hot streak, professionally handled.",
    "This isn't fair to the others. Or to me. Or to god.",
    "Witness a problem, in real time.",
    "Streak king. Streak queen. Streak menace.",
    "On a heater. Get them water. And a chastity belt.",
    "Trivia monk in their flow state.",
    "Cooking. With gas. And spite.",
    "Streak alert. Sound the alarm. Lock the doors.",
  ],
  elimination: [
    "And another one bites the drop, you sweet dumb bastard.",
    "Wrong. Try faster next time. Or smarter. Either works.",
    "That was a guess, wasn't it. Don't lie.",
    "Oof. Take a seat. Take a drink. Take a hike.",
    "Painful. Educational. Mostly fucking painful.",
    "Goodbye, sweet contestant. We barely tolerated you.",
    "Lights out on that one.",
    "Wrong button, wrong answer, wrong day, wrong outfit.",
    "And just like that — gone. Like my last paycheck.",
    "We hardly knew ye. Hardly wanted to.",
    "Dropped like a hot opinion at a family dinner.",
    "Sayonara, scholar. Don't let the door hit your ass.",
    "Filed under: nope.",
    "That's a swing and a whiff. A magnificent one.",
    "Take the L. Wear it well. Frame it. Show your kids.",
    "Brave guess. Wrong guess. Big balls, small brain.",
    "Off the board. Onto reflection. Possibly therapy.",
    "Better luck next century, dumbass.",
    "Plot twist: it wasn't that one. Womp womp.",
    "Goodbye, dear traveler.",
    "Misread. Misclicked. Mislived.",
    "Press F to pay respects. Then F off.",
    "Wrong. Confidently wrong, even. The worst kind.",
    "Yikes. Catalog that one. Frame it.",
    "Dropped from the running. Eat ass.",
    "And. Gone.",
    "Cataclysm, small scale.",
    "Misfired. Spectacularly. Magnificently. Painfully.",
    "Out. Cold. Done. Cooked.",
    "Welcome to wrongtown. Population: you.",
    "Take a bow. A short one.",
    "Off the cliff, that one. With style.",
    "Soft landing on the L.",
    "Confidently incorrect. A classic move from a classic dumbass.",
    "Painful. But brief. Like most regret.",
    "Goodbye, gambler.",
    "Wrong, but with conviction. Almost respectable.",
    "Filed under: try again, dipshit.",
    "Walked directly into that. Eyes open. Brain off.",
    "Dropped like the question owed money.",
    "Eliminated. With prejudice.",
    "Off the board. Off the brand. Off the rails.",
    "Tile down. Pride down with it.",
    "Wrong answer, big confidence. Goodbye, beautiful idiot.",
    "Swing and a miss. A dramatic, theatrical miss.",
  ],
  leader_changed: [
    "New leader! The throne is wobbly as shit.",
    "Coup at the top of the board. Bloodless. Mostly.",
    "Watch yourself, last round's winner. Your ass is exposed.",
    "Lead change! The peasants revolt.",
    "Old king is dead. Long live the new king. Or queen. Or whatever.",
    "Upset at the top. Drama, drama, fuckin drama.",
    "Power shift. The board never lies. Unlike your tinder profile.",
    "We have a new front-runner. For about ten seconds.",
    "Someone just snuck into first. Sneaky little goblin.",
    "Leaderboard reshuffled. Try to keep the fuck up.",
    "Fresh face at the top. Welcome. Watch your back.",
    "Coup successful. No bloodshed. Yet. Stay tuned.",
    "The standings just got interesting. And horny.",
    "Number one slot: under new management.",
    "Hostile takeover in progress.",
    "The crown changes heads.",
    "Old leader, we knew you well. Briefly. Reluctantly.",
    "Watch your back, top dog.",
    "Lead changed hands. Drama level: up. Pants level: down.",
    "And there it goes — first place. Like a fart in the wind.",
    "New name on the marquee.",
    "Reigning champ dethroned. Briefly? Probably not.",
    "Power vacuum filled. Quickly. Forcefully.",
    "Top of the pile just changed. The pile is mostly bullshit.",
    "Plot armor revoked, former leader. Cry it out.",
    "Throne up for grabs. Grabbed. Forcefully.",
    "New ruler installed. No ceremony. No condom.",
    "Leaderboard: under new ownership.",
    "Coup. Clean. Confirmed.",
    "Number one is now number two. Number two is just shit.",
    "Quiet climb. Loud takeover.",
    "Top spot rotated.",
    "Sneak attack on first place. Worked, you absolute weasel.",
    "And just like that — new king. New problems.",
    "Crown swapped mid-round.",
    "Lead changed. Egos changed. Underwear unchanged.",
    "Old champ, meet the floor.",
    "First place: now plural-ly contested.",
    "Climbed and conquered.",
    "Watchtower has a new tenant.",
    "Throne change! Politely uncivil.",
    "New name at the top. Adjust your bets. Adjust your pants.",
    "Power swap. Quiet coup.",
    "Leader change. The board breathes. The losers seethe.",
    "Top spot reassigned. Drama logged.",
  ],
  final_hype: [
    "This. Is. The Final fuckin Drop. Bet big or go home small.",
    "One question. Everything on the table. Try not to shit yourself.",
    "Final round. The standings mean fuck-all now.",
    "All chips in. All gloves off. All pants — your call.",
    "This is where legends are made — or memes. Mostly memes.",
    "Make it count. Or don't. I'm getting paid either way.",
    "Bet brave or bet broke. Your fuckin call.",
    "One more. Everything to lose. Have fun, you sweet idiot.",
    "Final question incoming. Try to breathe through your eyelids or whatever.",
    "The big one. Don't blink. Don't piss.",
    "Last call. Order something brave.",
    "Endgame. Pick a side. Pick a god.",
    "Final boss energy.",
    "No safety net from here. Just concrete.",
    "One question between you and immortality. Or eternal humiliation.",
    "Pressure check. How's the pulse? How's the colon?",
    "Final answer. Make it your best one.",
    "Curtain call. Take a swing.",
    "All or nothing. Mostly nothing.",
    "Last shot. Aim true. Aim drunk. Whatever.",
    "This is the one they'll remember. And mock.",
    "Final form. Activate.",
    "Down to the wire. Tighten the asscheeks.",
    "One question, infinite regret. Choose well.",
    "Last drop. Make it land.",
    "Sweat now. Brag later. Maybe.",
    "End boss. No retries. No mercy.",
    "Final answer. No takebacks. No refunds.",
    "Big swing time. Don't fuckin miss.",
    "This is the one. Be brave.",
    "Lights brighter. Stakes higher. Pants tighter.",
    "Coin flip with consequences. Serious consequences.",
    "Final drop. Hold on for dear life.",
    "Last frame. Make it pretty.",
    "Nothing left but the swing.",
    "Wager bravely. Cry quietly.",
    "End scene. Or beginning. Up to you, drama queen.",
    "Big moment. Bigger nerves. Biggest regret.",
    "Knock it down. Or get knocked.",
    "Final breath. Final answer.",
    "Wager everything or wager nothing. Both are personality disorders.",
    "Last question. Don't fumble the bag.",
    "All in or all out. There is no medium. There is no chill.",
    "This is the last one. So make it dumb or make it big. Or both.",
    "Closing question. Closing arguments. Closing tabs in case you cry.",
  ],
  credits_open: [
    "And that's the fuckin show. Roll credits.",
    "Game over. Survivors, please bow. Losers, please leave.",
    "Take a bow, contestants. Or don't, last place. Just go.",
    "That's a wrap. Thanks for the chaos.",
    "Show's done. The trivia gods rest. The trivia gods get a drink.",
    "Curtains. Hug your neighbor or don't. Probably don't.",
    "All over. Until next time, you sweet idiots.",
    "And we're out. Mic dropped. Pants dropped.",
    "Lights up. Pride down. Good night.",
    "That'll do, contestants. That'll fuckin do.",
    "Fin. Roll the names.",
    "We're done here. Go drink water. Or vodka. Your call.",
    "The end. Tip your trivia host. Venmo is on the screen.",
    "Game closed. Friendships pending review.",
    "That was a thing. It happened. We can never unsee it.",
    "Wrap it up, we're fuckin cooked.",
    "Final whistle. Hit the showers. Wash the shame off.",
    "Show over. Go touch grass. Touch each other. Whatever.",
    "Closing time. You don't have to go home, but you can't fuck here.",
    "The book is closed.",
    "And scene.",
    "Outro music. Imagine it horny.",
    "Thanks for playing. Or whatever.",
    "Until the next round of regret.",
    "Goodnight, sweet contestants.",
    "House lights up. Pride down. Pants — your call.",
    "Roll the credits. Roll the eyes. Roll a joint.",
    "All done. All judged.",
    "Game banked. Stories written. Texts sent that shouldn't have been.",
    "That'll do. Truly.",
    "Curtain. Bow. Leave. Don't text me.",
    "We out. Be good. Be safe. Be smart. Pick one.",
    "Show shipped. Egos refunded.",
    "Lights, names, doors. Use 'em.",
    "Take the memory. Leave the cup.",
    "Final whistle. Hands up. Pants down. Wait, no, just hands up.",
    "Closing time, scholars.",
    "Goodbye. Probably forever. Hopefully.",
    "Cheers. To the chaos. To the carnage.",
    "Until next round of mayhem.",
    "Goodnight, scholars and stumblers.",
    "That's all, folks. Tip your buzzer. Tip your bartender.",
    "Roll the names. They earned it. Some of them.",
    "Game closed. Group chat reopened. May god help you.",
    "Drive home safe. Argue gently. Fuck respectfully.",
  ],
  comeback: [
    "Somebody just climbed. Pay fuckin attention.",
    "Back from the dead. Welcome. Spooky.",
    "Quiet comeback. Loud consequences.",
    "Resurrection arc, confirmed.",
    "Someone just made a move. Big one. Sweaty one.",
    "Climber alert. Threat level rising. Pants tightening.",
    "Don't look now — somebody's back. Brace.",
    "Sneak attack from below. Don't ask.",
    "And just like that, back in it. Annoying.",
    "Plot twist incoming.",
    "Comeback engaged. Sirens optional. Boners optional.",
    "Quiet build. Loud finish. Theatrical.",
    "Climbed back into the chat.",
    "Whoever was sleeping just woke the fuck up.",
    "Don't blink. They moved up. Sneaky.",
    "Reentry confirmed. Hot. Spicy.",
    "Back from the basement. And the bottle.",
    "Threat reassessment time.",
    "Climbing. Quickly. Rudely.",
    "Someone remembered how to play.",
    "Late bloomer alert.",
    "Off the canvas, back swinging, mildly horny.",
    "Quiet riser. Suddenly loud.",
    "Back in the running. Annoying.",
    "Climb in progress. Yikes for everyone else.",
    "Underdog mode: activated.",
    "Climbing the ranks. Casually devastating.",
    "Welcome back to relevance, asshole.",
    "Someone's making a run for it. Catch them if you can.",
    "Resurrection complete. Cancel the funeral.",
    "From basement to threat. Quick fuckin work.",
    "Climbing the ladder, quietly menacing.",
    "Comeback arc, fully unlocked.",
    "Look who decided to play.",
    "Phoenix mode engaged.",
  ],
  round_recap: [
    "And that's the round. Lock it in, ya animals.",
    "Round done. Egos shuffled.",
    "Lights out on that round. Next.",
    "Round wrapped. Damage assessed. Bills pending.",
    "Scoreboard locked. Drama logged.",
    "And we're through. Onto the next clusterfuck.",
    "Round in the books. Bruises too.",
    "Take a breath. Round done.",
    "That round's a memory now. A bad one.",
    "Round closed. Lessons learned. Probably not.",
    "Survivors, regroup.",
    "Round filed. Onto chaos.",
    "Round one for the books. Or two. Who's counting. Me.",
    "Scoreboard updated. Egos noted. Erections logged.",
    "Round done. Try not to spiral.",
    "Cleared. Reloaded. Reset.",
    "That round's over. Heal up.",
    "Reset the brain. Next round in.",
    "Round burned. Onto the next.",
    "Scoreboard breathes. You don't.",
    "Tally locked. Pride floating.",
    "That round did damage. Sue me.",
    "Round complete. Audit pending.",
    "Wrap that round. Plate the next.",
    "Round filed under: yikes.",
    "Round over. Therapy later.",
    "Score recorded. Karma noted. Bar tab climbing.",
    "And that round happened. Moving on.",
    "Round closed. Boots laced.",
    "Round done. Quick stretch. Quick drink.",
    "Round filed. Lessons unlearned.",
    "Tape stops. Standings shift.",
    "Round over. Egos itemized. Receipts kept.",
    "And that was that. Onward, ya dingdongs.",
    "Round closed. Vibe recalibrating.",
  ],
  idle_interject: [
    "Don't make me start humming Wonderwall.",
    "Some of you are thinking too fuckin loud.",
    "I can hear the wifi struggling. And the asscheeks clenching.",
    "Take your time. I have notes. Mean ones.",
    "While we wait — I'm judging. Hard.",
    "Awkward silence is a love language. Mine, mostly.",
    "Anybody home? Cool, cool, cool.",
    "I'm filling space. You're welcome.",
    "The brain you ordered is loading. Buffer at 12%.",
    "Beautiful pause. Painful pause. Slightly horny pause.",
    "I'd hum, but I'm contractually quiet. And bitter.",
    "Stretching. Mentally. Hamstring-ly.",
    "Just me and the dead air.",
    "Pretend this is suspense. Pretend hard.",
    "I've seen toast move faster.",
    "Holding pattern. Engaged.",
    "Don't peek at your neighbor. Unless it's hot. Then peek.",
    "We're cool. Just standing here. Slowly dying.",
    "Pause for dramatic fuck-all.",
    "I'll just be here. Existing. Reluctantly.",
    "Real moment, this. Real shitty moment.",
    "Quietly judging. Loudly waiting.",
    "Buffering, are we.",
    "Polite pause continues.",
    "Crickets. Beautiful, professional crickets. Slightly horny crickets.",
    "Anyone? Bueller? Bueller's dad?",
    "Take your time. Or don't. I have nowhere to be. Sadly.",
    "Just vibing. Tactically.",
    "Hold music in my head. It's German techno.",
    "Awkward, isn't it.",
    "I'll wait. Loudly.",
    "Dead air is my comfort zone. And my therapist's nightmare.",
    "Time is a flat circle. So is your hesitation.",
    "Take all the time you need. Spoiler: don't.",
    "I'm aging in real time over here.",
  ],
  round_transition: [
    "Round two. Heating up.",
    "Round three. Gloves coming off. Possibly pants.",
    "Next round. Sharper questions. Dirtier looks.",
    "Round change. Egos repacking.",
    "And we shift gears. Probably grind a few.",
    "New round. New regrets.",
    "Fresh round, same chaos.",
    "Onto the next. Tighten the fuck up.",
    "Round flips. Pressure rises.",
    "Reset. Reload. Replay.",
    "New round in. Stay sharp.",
    "Onward. Upward. Possibly downward. Probably downward.",
    "Round forward. Bring brains.",
    "Up a level. Don't drop the controller. Or the drink.",
    "Round advances. So does pain.",
    "Next round drops.",
    "Round shifted. Score still mean.",
    "New round, new hostility.",
    "Onto the next chapter.",
    "Lights up. Round two-ish.",
    "Round changes. Faces stay nervous.",
    "Fresh round. Old grudges.",
    "Up next. Brace.",
    "Forward we go.",
    "Next round live. Hold tight.",
    "Round transition. Buckle in.",
    "Stage shifts. Stakes follow.",
    "Round to round, no break.",
    "And we roll into the next.",
    "Round flips. Drama follows.",
    "New round. Same energy. Worse questions.",
    "Round shift. Posture check.",
    "We pivot. You panic.",
    "Round changeover. Brace.",
    "Next round inbound. Eyes up.",
  ],
  wooden_spoon: [
    "Wooden spoon. Try harder, dipshit.",
    "Last place. Somebody had to. Sorry it was you.",
    "The floor called. It misses you. It also has questions.",
    "That round was a hate crime against trivia.",
    "Found a way. The wrong way. The very wrong way.",
    "Dead last. Eat your veggies. And your shame.",
    "Bottom of the barrel. Cozy in there?",
    "Polished the floor that round. Slippery work.",
    "Caboose energy. All round.",
    "You brought a sundial to a stopwatch fight.",
    "Last place, big confidence. Iconic disaster.",
    "Trivia 0, vibes 1, dignity bankrupt.",
    "The basement called. You moved in. You unpacked.",
    "Took the L with style. Barely.",
    "Wrong button. Every fuckin time.",
    "Anchor of the room. We salute you.",
    "Last. Loud. Lovable. Largely lost.",
    "Score sheet says no. Loudly.",
    "Round goblin spotted. In last. Naturally.",
    "Bottom of the heap. Cozy, isn't it.",
    "Last place earned, fair and square.",
    "Wooden spoon, fully polished. Slightly suggestive.",
    "Floor's all yours. Don't track mud. Or shame.",
    "Last. Locked in. Loud. Lubricated.",
  ],
  goose_egg: [
    "Big fuckin zero. Reflect on that.",
    "Brought a knife to a knowledge fight. A butter knife.",
    "Round of nothing. Powerful.",
    "Goose egg. Lay another one.",
    "Zero points, full commitment.",
    "Round one stat: vibes. That's the whole stat sheet.",
    "Nothing on the board. Bold fuckin strategy.",
    "Scored nothing. Made memories. Bad ones.",
    "Empty stat line. Loud personality. Big delusion.",
    "Zero. The cleanest number. The cleanest L.",
    "Donut for that round. Hot. Greasy.",
    "Nada. Zip. Vibes intact.",
    "Stat line: a perfect circle.",
    "Negative knowledge that round.",
    "Did nothing. Looked great doing it. Probably.",
    "Pure zero. Almost zen.",
    "A donut so big I want it framed. And eaten.",
    "Round score: emotional damage only.",
    "Zero. With style. With swagger. With shame.",
  ],
  last_to_lock: [
    "Cutting it fuckin close, that one.",
    "Last in. Living dangerously.",
    "Buzzer-beater. Barely. Sweatily.",
    "Squeaked it under the wire.",
    "Last call locked. Heart rate noted.",
    "Made it. By a whisker. By a pube.",
    "Final answer, final second.",
    "Right on the buzzer. Audacious.",
    "Tap heard 'round the lobby.",
    "Last in. Cool under fire. Hot under collar.",
    "Sneaky-late. Suspicious as hell.",
    "Cutting time like a magician on a deadline.",
    "Buzzer kissed. Brave. Slightly horny.",
  ],
  random_jab: [
    "We see you back there, ya silent menace.",
    "Don't forget you exist. We barely have.",
    "Plotting something. Probably horny.",
    "Quiet. Suspicious as fuck.",
    "Lurking. Calculating. Mid as hell.",
    "Vibing. Not winning. Vibing.",
    "Energy: present. Score: pending. Pants: questionable.",
    "Showing up counts. Slightly.",
    "Quiet competitor. Suspicious.",
    "Saving energy for round seventeen. Cute, dumbass.",
    "Mysterious. Mostly inert.",
    "Background character energy. Promising.",
    "Plotting in silence. Or napping. Probably napping.",
  ],
};
