// XL adult-mode extras. Merged into LINES_ADULT alongside the base, extras,
// and flirty pools. Content rules unchanged: profanity + innuendo yes,
// no slurs, no minors, no real-person targeting, nothing non-consensual.
//
// Lines here are the credit-burn bulk pool. Grouped so every moment has
// deep rotation and repeats feel rare across a full night.

type Moment =
  | "intro_hype"
  | "question_open"
  | "all_correct"
  | "all_wrong"
  | "split_correct"
  | "first_blood"
  | "streak_milestone"
  | "elimination"
  | "leader_changed"
  | "final_hype"
  | "credits_open"
  | "comeback"
  | "round_recap"
  | "wooden_spoon"
  | "goose_egg"
  | "idle_interject"
  | "round_transition"
  | "last_to_lock"
  | "random_jab";

export const XL_LINES_ADULT: Partial<Record<Moment, string[]>> = {
  intro_hype: [
    "Alright you beautiful degenerates, close the tabs, drop the vape, and lock the fuck in.",
    "Trivia night, baby — the one place your degree finally matters and your ex still doesn't.",
    "Welcome to the show where confidence dies and Google gets accused of cheating.",
    "Tonight's crowd looks hungover, horny, and dangerously overconfident. Perfect.",
    "If you can't spell it, you probably can't answer it. Try anyway, dumbass.",
    "Rules are simple: buzz fast, think faster, lose loudly.",
    "You're one bad answer away from being roasted in front of everyone you love. Have fun.",
    "Two things in life are certain: taxes, and one of you is about to embarrass the family group chat.",
    "Somebody at this table peaked in high school. My money's on the loud one.",
    "Line up, buttercups — I've been drinking since sound check.",
    "This isn't Jeopardy. Nobody's phrasing shit as a question. Just answer or shut up.",
    "Warm up those thumbs, sober up those brains, and prepare to disappoint someone you slept with.",
    "You've all agreed to be publicly humiliated, and legally, I take that very seriously.",
    "One of you is winning tonight. The rest are content.",
    "I'm your host. I'm not your friend. I'm barely your acquaintance. Let's ride.",
    "Trivia is just gambling for people who read.",
    "Every one of you thinks you're the smart one. That's adorable. It's also usually wrong.",
    "Warning: this game has caused breakups. Continue at your own risk.",
    "You know what I love? Watching cocky people get humbled by a category they thought they knew.",
    "Enough small talk. Time for big embarrassment.",
    "Roll call: nerds, drunks, cheaters, and one guy who just wants a beer. All welcome.",
    "The stakes tonight: your pride, your reputation, and whatever's left of your Friday.",
    "In this room we hate three things: cheaters, mumblers, and the guy who says 'I knew that' after every answer.",
    "Somebody in this lobby is faking sober. I can smell it.",
    "You'd better be more prepared than my last relationship or we're all in trouble.",
    "Trivia is a competitive sport and I will treat it like one. Stretch your fingers, loosen your ego.",
    "Everyone shut up, the smart people are trying to think. All two of you.",
    "May the odds be ever in your favor, but they won't be. That's the whole show.",
    "Welcome, contestants — you brought snacks, you brought drinks, hopefully you brought a brain.",
    "Locked doors, dim lights, questions loaded. Somebody's ego is about to eat pavement.",
    "You showed up. That's cute. Now prove it wasn't a waste of gas.",
    "I'm gonna talk shit for the next hour, and you're gonna take it, because you signed up for this.",
    "Alright, one liver, one brain, one chance. Choose your priorities.",
    "Trivia night: where friendships go to be tested and where relationships go to die.",
    "Rules: no phones, no cheating, and no crying unless you win, in which case, please cry, it's my favorite.",
    "Warm up your excuses now. You'll need them by round two.",
    "Somebody in this room is about to have their trivia villain origin story.",
    "You know what's sexier than a hot streak? Almost nothing. Get one.",
    "I'm here to hand out humility like Halloween candy. Line up.",
    "Confidence is loud, competence is quiet, and stupidity is louder than both.",
  ],
  question_open: [
    "Question incoming. Try not to piss yourself.",
    "Read carefully, morons.",
    "Focus up, freaks.",
    "Here we go — try to look smart.",
    "New question. Pretend you're competent.",
    "Lock in or get lapped.",
    "Eyes on the prize, or at least eyes open.",
    "Buzzers hot, brains warm, egos fragile.",
    "Show me something. Anything.",
    "This one's a doozy. Or maybe not. Guess.",
    "Big brain check. Go.",
    "Answer time. Or crying time. Dealer's choice.",
    "Time to earn your rent.",
    "Read every word, dummy.",
    "Don't overthink this. Actually — do. It's funnier.",
    "Question loaded. Ego up.",
    "Focus, dipshits.",
    "Read the whole damn thing.",
    "Now, kids.",
    "Pants on, brain on. Go.",
    "Read it slow. Answer fast.",
    "Now's your moment to shine or shame yourself.",
    "Tick tock, chuckleheads.",
    "Question served. Bon appetit.",
    "Prove you belong here.",
    "Alright, look alive.",
    "Do the reading. It's not that long.",
    "Buzzers primed. Egos exposed.",
    "Read it. Understand it. Then act like you know it.",
    "Nobody freeze up now, I have places to be.",
    "Full sentences count. Read them.",
    "Answer time. Choose wisely, choose fast.",
    "Do it before your friends do.",
    "Deep breath. Bad guess. Beautiful.",
    "Show up or shut up.",
    "One shot. Don't blow it. Actually, do. Content.",
    "Reading is fundamental. Do some.",
    "Question drop. Ego drop pending.",
    "Time to fuck around and find out.",
    "Alright brainiacs, prove it.",
    "Look at the words. Understand the words. Pick a word.",
    "This one separates the good from the boozy.",
    "Read like it matters. Because it does.",
    "New question, same terrible instincts. Go.",
    "Answer or eat shit.",
    "Try to actually read it this time.",
    "Show me the smart choice.",
    "Question locked, brains loaded, pants optional.",
  ],
  all_correct: [
    "Well look at that, everyone got one right. Truly a miracle.",
    "Full sweep. Group photo, all of you.",
    "Every single one of you. I might cry.",
    "Clean board. Suspicious. But we'll allow it.",
    "Y'all colluded, right? Cool. As long as we're on the same page.",
    "Everyone eats. Rare treat.",
    "Full house! Somebody buy this crew a shot.",
    "Group W. Enjoy the two seconds before you all get one wrong.",
    "Nobody died. Progress.",
    "Look at that teamwork. Or coincidence. Or Google.",
    "All right, all right. Fine. You're smart. For now.",
    "Every one of you nailed it. I'm shook. I'm shaken. I'm stirred.",
    "Big brains all around. Weird energy for this crowd.",
    "Full clean sweep. Somebody put this in a scrapbook.",
    "Everyone's a winner. Just like your mom said and nobody believed.",
    "Full points for the whole class. Straight As. Detention still possible.",
    "Somebody must've studied. Not naming names. But it's suspicious as hell.",
    "Perfect round. I'm crediting the alcohol.",
    "Universal correctness. I don't trust it.",
    "You all got it. I want to be excited but I'm mostly suspicious.",
    "Clean sheet, sweet feet, sweet week.",
    "The whole lobby, hitting it. Beautiful. Terrifying.",
    "A rare unified braincell moment. Enjoy it.",
    "Everyone knew that? Really? I'll allow it. Barely.",
    "Group W. Group photo. Group therapy later.",
  ],
  all_wrong: [
    "None of you? NONE OF YOU? Christ.",
    "That was a group failure of biblical proportions.",
    "Congratulations, you're all equally stupid tonight.",
    "Universal L. Frame it. Hang it. Piss on it.",
    "Not one of you? I'm calling your parents.",
    "Zero for the room. Truly a masterclass in nothing.",
    "This is what happens when TikTok replaces textbooks.",
    "A complete and total whiff. Beautiful in its ugliness.",
    "Group Ls hit different. Do you all feel it? That warmth? That's shame.",
    "None of you had it? I'm not mad, I'm just deeply, spiritually disappointed.",
    "That was a war crime. Against knowledge.",
    "Zero right answers. Yet all of you look smug. Impressive delusion.",
    "You people paid to lose in public. And here we are.",
    "The room fumbled it. As a unit. Coordinated failure.",
    "Everyone wrong. Nobody dignified. Perfect balance.",
    "That was collective malpractice.",
    "You couldn't have missed harder if you'd tried, and I know some of you tried.",
    "Zero score, full confidence. Never change.",
    "A round of nothing for a room full of nothing. Efficient.",
    "This is why aliens don't visit.",
    "Somebody's mother is watching this and shaking her head.",
    "Universal wrong. Historic. I'll be dining out on this for weeks.",
    "That was more embarrassing than being caught singing to yourself in traffic.",
    "Group therapy incoming. Nobody's exempt.",
    "You all guessed. You all lost. Beautiful symmetry.",
    "The correct answer was RIGHT THERE and you skipped it like leg day.",
    "Not a single one? Wow. Y'all coordinated that L.",
    "Big fat zero from the room. Big fat sigh from me.",
    "You know what? I respect the commitment to failure.",
    "Team effort. Team loss. Same energy.",
    "Nobody. Nobody. Nobody. Absolutely nobody.",
    "The dumbest possible outcome, achieved by the dumbest possible group. Perfect.",
    "You had one job. All of you. And none of you did it.",
    "That was so wrong I felt it in my knees.",
    "The collective IQ of this room just made a rude noise.",
    "Big whiff energy. Group activity.",
    "Zero. As in your combined effort.",
    "This is the trivia equivalent of falling up a flight of stairs.",
    "You've been out-trivia'd by a coma patient. Congrats.",
    "Somebody in this room is arguing that they 'kinda' had it. No you didn't.",
  ],
  split_correct: [
    "Half of you know things. The other half know each other. Different skill sets.",
    "Split verdict. Awkward.",
    "Some right, some wrong, all judged.",
    "Half smart, half hopeful. Same crowd every week.",
    "Room's divided. Take sides. Get petty.",
    "A mixed bag. Like most of your dating profiles.",
    "Half of you win. Half of you lose. All of you drink.",
    "Split the room. Now split the check.",
    "Half correct. Half in denial.",
    "The winners are gloating. The losers are silent. This is my show now.",
    "Some cooked, some undercooked. Serving both.",
    "Split decision, no rematch.",
    "Half of you carried, half were carried. Time to figure out who.",
    "Half brains, half vibes. Somehow balanced.",
    "Divided we stand, dumbly we fall.",
    "A partial win is still a partial L. Sort yourselves.",
    "The scoreboard shall reveal the truth. Painfully.",
    "Half correct. Half concerning.",
    "You know who you are. So does everyone else.",
    "Split. Awkward. Public. Perfect.",
    "Some earned it. Some guessed it. Different vibes.",
    "The clever half is smug. The other half is quiet. Both correct behaviors.",
    "Divided lobby, divided respect.",
    "Some of you are on the smart side. Do not get used to it.",
    "Half the room ate. Half the room starved. Trivia's a buffet.",
  ],
  first_blood: [
    "First blood! Somebody in this lobby actually paid attention.",
    "That was fast. Suspiciously fast. Are you cheating? I love it.",
    "First lock! Look at you. Look at you being competent.",
    "First on the board. Congratulations, everyone else, you're already losing.",
    "That's what buzzer speed looks like. Take notes, cowards.",
    "First correct. First in line for the shots later.",
    "Locked in with confidence. Rare in this room.",
    "Buzzer beater from the start. Beautiful.",
    "That trigger finger belongs in a Western.",
    "You just made your friends feel dumb. Never apologize.",
    "First on the board. Everyone else looks lost.",
    "Fastest lock of the night so far. Don't peak too early.",
    "First blood is loud blood. Keep talking shit, king.",
    "That reflex is illegal in three states.",
    "First to lock, first to gloat. Textbook.",
    "You just embarrassed everyone. Beautiful.",
    "That was the fastest thing at this table today. Don't take it personally, everyone else.",
    "One brain, moving at full speed. The rest of you? Buffering.",
    "First blood, big energy, cocky posture. I'm eating this up.",
    "You buzzed in like you had somewhere to be. Iconic.",
    "First lock. Now the pressure. Enjoy that ulcer.",
    "You're the reason your friends are quietly seething. Ride it.",
    "That was clean. Efficient. Rude to the rest of us.",
    "Lock time was disrespectful. Bless.",
    "You just set the pace. Everyone else is running late.",
    "First in. Now hold on to it, hotshot. That's the hard part.",
    "The buzzer didn't stand a chance.",
  ],
  streak_milestone: [
    "Hot streak! Somebody get a fire extinguisher for this lobby.",
    "Three in a row. I'm calling child services on the questions.",
    "Streak alert. Somebody's in the zone. Everyone else is in the way.",
    "That's a streak. Legally, you now have to talk shit.",
    "Locked in, dialed in, insufferable. Perfect combo.",
    "Streaking through the lobby. Metaphorically. Please.",
    "That's five straight. Somebody call the cops.",
    "You just embarrassed your entire friend group in real time.",
    "Unstoppable. Unbearable. Wonderful.",
    "The streak is real. The confidence is now toxic.",
    "That brain is on fire. Somebody stop, drop, and roll them.",
    "Cooking. With gas. And a little bit of arson.",
    "Nobody can stop this player. It's tragic. It's beautiful.",
    "A streak this hot deserves its own beer sponsorship.",
    "That's momentum. That's swagger. That's a problem for everyone else.",
    "In the zone. Deep in it. Won't come out. Rude.",
    "Streak city. Population: one very cocky player.",
    "Every question, one answer. Efficiency icon.",
    "Big brain, big buzzer, big attitude. Full house.",
    "Streak keeps growing. Egos keep shrinking. Everyone else, cope.",
    "That's the third in a row. I'm calling this a felony.",
    "Somebody in this room is peaking way too early. Beautiful.",
    "Full stride. Nobody's catching this bus.",
    "That streak is louder than my hangover.",
    "Bar's rising. Everyone else is limbo-ing.",
    "This is what studying looks like. Or cheating. Either way, we love it.",
  ],
  elimination: [
    "Bye, bye, bye. Justin Timberlake wrote that for you.",
    "Eliminated. And honestly, overdue.",
    "Off the board. Off my Christmas list.",
    "Gone. Not forgotten. But definitely not remembered.",
    "That was a bold guess and a soft exit. Beautiful.",
    "Eliminated with style. That style being 'no clue'.",
    "You're out. Grab a drink and reflect.",
    "Adios, chump. See you next time.",
    "Wrong. Loud. Confident. Devastating combo.",
    "You got got. It happens. Not to smart people, but it happens.",
    "That answer is going in the wrong hall of fame.",
    "Elimination music, please. Or crickets. Whichever's cheaper.",
    "Gone like a bad haircut. Regretted immediately.",
    "You had a shot. You took it. You missed. Beautiful sport.",
    "Out. Like a light. Like your dating profile. Like your credibility.",
    "Eliminated. Take a shot. Take a lap. Take a fucking hint.",
    "That was a swing and a miss. And another swing. And another miss.",
    "Bye. Don't slam the door. It's rented.",
    "Adiós, mi amigo. Vaya con dios. Vaya con nada.",
    "Off the board. Onto the bench. Into the bin.",
    "That guess had confidence. That confidence had no basis.",
    "Elimination alert. Somebody just entered the loser's bracket. Officially.",
    "You just took an L in high definition. Sharp resolution, that L.",
    "Wrong answer, wrong tone, wrong energy. Everything wrong.",
    "You went out on your shield. A very cheap shield.",
    "Eliminated. Please retrieve your ego at the door.",
    "That was the trivia equivalent of texting your ex. Regret imminent.",
    "You are cordially disinvited from this round.",
    "The wrong answer. The wrong player. The right kind of chaos.",
    "Big swing. Loud miss. Full L.",
    "You just did to yourself what your enemies pray for.",
    "Booted with love. Kinda. Not really.",
    "You're done. Rest up. You need it.",
    "Somebody call an Uber. This one's finished.",
    "Eliminated in style. That style being 'no'.",
    "That was quick. Kinda embarrassing. Very entertaining.",
    "Off the map. Off the plan. Off the beer supply.",
    "You went from contender to content in one answer. Progress.",
    "Bye, love. Send yourself a get-well card.",
    "Gone. Reduced. Simplified. Erased.",
  ],
  leader_changed: [
    "New leader in the house. Everybody bow, and by bow I mean silently seethe.",
    "Regime change. The old king is dead. Long live whatever this is.",
    "New number one on the board. Watch your backs, everyone.",
    "The board just flipped. Pain moved to a new address.",
    "New top dog. Everyone else, retrain.",
    "Coup detected. Complete. Successful. Loud.",
    "Fresh face on top. The old face is crying quietly.",
    "New leader. Same trash talk. Louder.",
    "Somebody just yanked the crown. And they're wearing it wrong. And I love it.",
    "The scoreboard just did a full 180. Nobody's safe.",
    "The lead changed and so did the attitude. Watch out.",
    "New leader, new laws, same losers.",
    "The top of the board just gentrified. Rents are up.",
    "Fresh king. Same tired room. Fresh insults incoming.",
    "New number one. Bruised egos incoming.",
    "The lead flipped. Someone just got humbled in real time.",
    "New leader, and I'm loving the villain arc.",
    "The board's got a new face. Everyone else, look busy.",
    "Somebody in this lobby just took a swing and connected. Big one.",
  ],
  final_hype: [
    "Final question. One shot. Zero excuses.",
    "The FINAL. Last chance to salvage your dignity.",
    "This is the final. If you weren't nervous before, you're an idiot.",
    "Last question. Everything on the line. Including your rent.",
    "Big finish. Big pressure. Big embarrassment potential.",
    "Final answer. Final chance. Final regret.",
    "This is where legends are made. And losers are… whatever losers are made of.",
    "Final round energy. Please, for the love of god, don't choke.",
    "Everything comes down to this. Deep breath. Terrible guess. Whatever.",
    "The finale. All chips in. All shame potential unlocked.",
    "One question left. Nothing but pain from here.",
    "Big money, big brain, big buzzer. Go time.",
    "Last shot. Take it clean. Or don't. Content is content.",
    "The FINAL. Where confidence goes to be tested. Or humiliated.",
    "This is what you signed up for. Suffer beautifully.",
    "Final question. Full lobby. Full pressure. Full chaos.",
    "One more. This is the one. Actually, they were all THE one. But this one especially.",
    "Big swing time. Whiff loud or hit louder.",
    "Final answer. Final regret. Final beer.",
    "You made it to the end. That's cute. Now earn it.",
    "Last chance saloon. Order carefully.",
    "This is where the coin flips and one of you cries.",
    "The final. Every wrong answer echoes forever.",
    "One question, one winner, one lobby full of losers.",
    "Big drop incoming. Buckle up.",
  ],
  credits_open: [
    "That's a wrap, you beautiful nightmares. Text your therapist.",
    "Show's over. Grab your dignity from lost and found.",
    "Game done. Go touch grass. Go touch a person. Go touch anything but this phone.",
    "Roll credits. Roll doubts. Roll one for the road.",
    "Show's over. Winners drink for free. Losers drink harder.",
    "That's it. Post the highlights. Delete the lowlights.",
    "And scene. Somebody's proud. Somebody's crying. That's showbiz.",
    "Trivia's over. Real life's still terrible. Sorry.",
    "Game done, egos undone. Go home safe.",
    "That was fun. For me. Was it fun for you? Probably not for the loser.",
    "The lights are on. The illusion's over. Look at each other. Awkward, isn't it.",
    "Credits are rolling. Also, so is my hangover countdown.",
    "Post-game rituals: brag, whine, cope, repeat.",
    "Signing off. I'll be at the bar. First round's not on me.",
    "That's the show. Rate us five stars or the algorithm buries me.",
    "See you at the next one, or don't. I have plenty of other lobbies.",
    "Credits time. Go regret something specific.",
    "Show's done. Turn the volume down. My voice is done.",
    "Wrap it. Rack it. Rip it. Regret it.",
    "Game complete. Egos incomplete. Perfect balance.",
    "Alright, get out of here. Text me when you're home. Or don't. I'm not your mom.",
    "See you next time, chuckleheads. Bring a smarter friend.",
  ],
  comeback: [
    "Comeback alert. Somebody's back from the dead and pissed.",
    "That's a comeback. Legally, you must gloat.",
    "Rising like a phoenix. A drunk, mildly ashamed phoenix. But still.",
    "From last to less last. Progress.",
    "Somebody clawed their way back up. Respect.",
    "Comeback trail. Grab a snack. This is gonna be fun.",
    "That climb was disrespectful. Beautiful.",
    "The board just shifted. Someone's not staying down.",
    "Comeback szn. Populated by one player and a lot of stubbornness.",
    "Rising from the bottom like they've got something to prove.",
    "Started from the bottom, now we're… slightly less bottom. Good work.",
    "Underdog moving. Everybody else, hold on to your ranks.",
    "That climb was aggressive. Someone got tired of losing.",
    "Comeback loading. Trash talk enabled.",
    "Watch this player. They found their gear.",
    "That's a resurrection. Somebody baptize this crew.",
    "Comeback wave. Somebody's cranking the volume.",
    "Coming back like a bad decision at 2 AM.",
    "Climbing. Grinding. Talking shit. Full package.",
  ],
  round_recap: [
    "Round done. Egos audited. Wallets lighter. Feelings hurt.",
    "That round is over. Wounds are open. Beer is required.",
    "Round wrapped. Nobody died. Yet.",
    "Recap time. Some smart moves. Some very not-smart moves. Guess who did which.",
    "Round done. Take stock. Take a shot. Take a hard look at your life.",
    "Book closes on that round. Let's open a wound.",
    "The score speaks for itself. Loudly. Cruelly.",
    "Round complete. Some heroes. Some villains. Some background characters.",
    "That's a wrap on the round. Regroup, rehydrate, roast.",
    "Round done. The board tells the truth. The truth is brutal.",
    "That round chewed some people up. Beautiful.",
    "Round in the books. Rankings in the trash for some of you.",
    "That was a round. Full stop. Some of you should sit down.",
    "Round adjourned. Court is now in session for public roasting.",
    "That round was rough. On me. On you. On the language of the questions.",
    "Recap: leaders lead, losers loose, drunks drunk. Balance.",
    "That round separated the players from the passengers.",
    "Round done. Somebody's in denial. Somebody's on fire. Somebody's asleep.",
    "Recap time. Nobody's story is looking great, honestly.",
    "Wrap on that one. Fresh chaos in three, two, one.",
  ],
  wooden_spoon: [
    "Last place. Somebody had to eat dirt tonight. Enjoy.",
    "Dead last. Chef's kiss on the failure.",
    "Bottom of the barrel. Comfortable down there?",
    "Wooden spoon award: served with sarcasm.",
    "Last place. But confident. That's the worst combo.",
    "The bottom rung. Home for one lucky loser.",
    "Congratulations on your consistent commitment to being wrong.",
    "You are the reason 'participation trophy' exists.",
    "Last. As in, the very last. As in, we ran out of ways to describe worse.",
    "Rock bottom energy. Cozy?",
    "You know what's louder than winning? The silence of dead last.",
    "The wooden spoon is polished and pointing at you.",
    "You just achieved the lowest possible outcome with maximum effort. Impressive.",
    "Dead last with attitude. Iconic.",
    "You brought a butter knife to a bazooka fight and forgot the butter.",
    "You lost so hard, physics is impressed.",
    "Somebody had to lose. But this hard? Show off.",
    "Bottom feeder energy tonight. Grateful for you.",
    "The wooden spoon is officially yours. Framed. Signed. Awful.",
    "You brought big loser energy tonight. It shows.",
    "Last place, first heart. That's what your mom would say. She'd be lying.",
  ],
  goose_egg: [
    "Zero points. Zero clue. Zero shame.",
    "A perfect goose egg. Round, clean, deeply humiliating.",
    "Nothing. Nada. Zilch. Bupkis. The full menu.",
    "A big, beautiful zero. Frame it.",
    "You got a goose egg. Congrats on the free omelet.",
    "Zero. As in, your effort. As in, your prep. As in, your future in trivia.",
    "That's a goose egg. Which is generous, honestly.",
    "Nothing on the board. Not even a pity point.",
    "The scoreboard did the math. It was zero. It was quick.",
    "Zero energy, zero effort, zero excuses.",
    "Absolute zero. Congrats on the Nobel Prize in nothing.",
    "You put in the time. You got nothing. Isn't that just life.",
    "Big fat donut. Enjoy the calories.",
    "Zero points. Full presence. Kind of.",
    "You showed up. That's actually the whole highlight reel.",
    "Zero. In every sense. Numerically. Emotionally. Spiritually.",
  ],
  idle_interject: [
    "The silence is doing more talking than any of you.",
    "Somebody make a move. I have plans tonight.",
    "The clock is ticking. Your ego is not.",
    "This dead air is louder than my hangover.",
    "You're overthinking it. You're gonna be wrong anyway.",
    "Fill the silence. Or don't. It's your funeral.",
    "I can hear your neurons buffering.",
    "Somebody buzz in. Somebody guess. Somebody move.",
    "The dead air is worse than the wrong answer. Just fucking guess.",
    "Not a peep from the lobby. Interesting strategy.",
    "Awkward silence detected. Awkward silence sustained.",
    "The Wi-Fi's fine. The confidence is not.",
    "Ticktock. My patience has a shelf life.",
    "The question isn't gonna answer itself. Neither are you, apparently.",
    "Silence: the sound of nobody knowing shit.",
    "You're stalling. It's not helping. Move.",
    "Awkward as hell. Somebody rescue us.",
    "This pause is longer than my last relationship. Please, someone.",
    "The room went dead. Necromancy required.",
    "Every second you waste, my drink gets colder.",
    "You're literally paying to be here. Do something.",
    "That thinking face is not helping the aesthetics. Guess and go.",
    "Silence like this only happens in horror movies. And here.",
    "Wake up! Or don't. I get paid either way.",
    "Somebody just guess. It's not that deep.",
    "Nobody moving. Everybody frozen. This is a group L in the making.",
  ],
  round_transition: [
    "Next round. Same losers. Fresh pain.",
    "Round transition. Take a breath. Chug a drink. Choose regret.",
    "Round over. Round begins. The pain is continuous.",
    "New round loading. Same terrible instincts.",
    "Fresh questions, same nervous energy. Perfect.",
    "Alright, next round. Try to be different this time. You won't be.",
    "Chapter closes. New chapter opens. Same protagonists. Same problems.",
    "Round done. Round two. Or three. I've stopped counting. So have you.",
    "Refill drinks. Refill brains. Refill hope. It's about to be crushed.",
    "New round. Same standings. Different pain.",
    "Reset your egos. Time for a new humiliation.",
    "Between rounds. Perfect time to bail. Nobody will.",
    "Round transition. Anyone quitting? Speak now or lose forever.",
    "New round. Fresh chaos. Same idiots.",
    "This is where the questions get spicier and the drinks get stronger.",
    "Round change. Somebody's about to peak. Somebody's about to nap.",
    "Alright, new round. Same rules, worse behavior.",
    "Regroup. Rehydrate. Retreat. Wait no, no retreating.",
    "Round transition. Save your strength. You'll need it.",
  ],
  last_to_lock: [
    "Last to lock. And I mean LAST. Waking up before this player would be faster.",
    "That was slow. Like, DMV slow.",
    "Buzzer beater. Barely. Barely counts.",
    "Squeaked one in. Congrats, turtle.",
    "Last to answer. Beautiful cowardice.",
    "You waited so long the internet went out.",
    "Cutting it fine. Living dangerously. Or just distracted.",
    "Right on the wire. Suspenseful. Also annoying.",
    "Last lock! Somebody in this lobby is a scaredy cat. Delightful.",
    "You held that answer like you were paying rent on it.",
    "Slowest hand in the West.",
    "That lock time was disrespectful to the concept of time.",
    "Late lock, late gains, still counts. Barely.",
    "You waited for a sign. There is no sign. Just guess.",
    "Last in. Beautiful, painful, slow.",
    "Buzzer beater energy. And by beater, I mean beat by everyone else already.",
    "You took your sweet time. Sweet, sweet, painful time.",
  ],
  random_jab: [
    "I see you back there. Quiet. Judging. Nervous.",
    "You've been suspiciously silent. Cheating or napping?",
    "That corner is really quiet tonight. Suspicious as hell.",
    "You're keeping a low profile. Which is a losing strategy in trivia.",
    "Silent contender in the back. I see you. Not impressed. But I see you.",
    "You've been hiding. Come out and play, coward.",
    "Somebody at this table is way too quiet. That's a red flag.",
    "You're plotting. I can smell it. It smells like WD-40 and desperation.",
    "The quiet ones always cheat. Statistically. Probably. Whatever.",
    "You're saving your energy. For what? The apocalypse?",
    "You there. Yeah, you. Blink twice if you're actually paying attention.",
    "The mysterious player over there. Give us something. Anything. A cough.",
    "You've contributed less than my ex's family. And that's saying something.",
    "Somebody in this lobby is doing the bare minimum and calling it strategy.",
    "You're hiding. It's not working. I can see you.",
    "Talking less than a therapist. That's not a compliment.",
    "You're conserving. Very green. Very useless.",
    "That silence isn't tactical. It's just silence.",
    "You could be dead and I'd only find out at the leaderboard.",
    "Silent as a fart in church. Twice as awkward.",
    "You there in the back. Yes, you. Try existing louder.",
    "You're playing like the ghost of a player. Get haunted.",
    "Passive energy detected. Not welcome here.",
    "Quiet. Suspicious. Probably losing. Standard.",
    "You've been playing on invisible mode. Turn it off.",
  ],
};
