// Host persona — "Vox", the in-game emcee.
// Catchphrases used by HostGameStage to react to game moments.
// Lines are intentionally short so the browser speechSynthesis voice
// (or a pre-baked TTS file) reads them in under ~3 seconds.

export const HOST_NAME = "Vox";

type Moment =
  | "intro_hype"        // cold open, after title card
  | "question_open"     // brand new question hits the screen
  | "all_correct"       // entire room got it
  | "all_wrong"         // entire room whiffed
  | "split_correct"     // some right, some wrong
  | "first_blood"       // first to lock and correct
  | "streak_milestone"  // 3+/5+/7+ streak
  | "elimination"       // wrong answer dropped
  | "leader_changed"    // new #1 on leaderboard
  | "final_hype"        // entering final round
  | "credits_open"      // outro credits start
  | "comeback"          // someone clawed back up the board
  | "round_recap"       // generic round-end zing
  | "wooden_spoon"      // lowest scorer of the round
  | "goose_egg"         // player(s) who scored zero
  | "idle_interject"    // dead-air filler between questions
  | "round_transition"; // between-round stinger

export const LINES: Record<Moment, string[]> = {
  intro_hype: [
    "Buckle up. The drop is coming.",
    "Fingers on buzzers. Egos at the door.",
    "Let's find out who actually paid attention in school.",
    "Welcome, contestants. And condolences in advance.",
    "Brains warm? Good. Let's break some.",
    "I hope you brought your A-game. B-game won't cut it.",
    "Shoes off, gloves on. We're going in.",
    "May the smartest survive. Or the luckiest. Whatever.",
    "Trivia night, baby. Don't embarrass yourselves.",
    "Let's see who came to play and who came to watch.",
    "Stretch those neurons. We start hot.",
    "No warm-ups. No mercy. Just questions.",
    "Hydrate. Focus. Lose with dignity.",
    "Friendships end tonight. That's the promise.",
    "Coffee in hand? Pride intact? Doesn't matter.",
    "I've seen the questions. You're cooked.",
    "Phones down, brains up. Let's ride.",
    "Tonight, somebody learns something. Probably about themselves.",
    "Welcome to the arena. Bring snacks for the loser.",
    "Lights up. Filters off. Game on.",
    "Strap in. The ride doesn't have a seatbelt.",
    "First question's a freebie. Maybe.",
    "Last person to lock in buys drinks. Kidding. Mostly.",
    "I'm legally obligated to wish you luck. Good luck.",
    "Let's make some memories. And some enemies.",
    "Doors locked. Lights hot. Let's play.",
    "I've been waiting. You're late.",
    "Confidence high? Good. We'll fix that.",
    "New game, fresh humiliation.",
    "Brains assembled. Mostly.",
    "Showtime. Try to keep up.",
    "Knuckles cracked. Buzzers primed.",
    "The questions are mean. So am I.",
    "Welcome in. Mind the bodies.",
    "Pencils down. Wait, wrong show.",
    "We start at the deep end.",
    "Lobby's closed. We ride at dawn.",
    "I picked the hard ones for you. You're welcome.",
    "Open hearts. Closed mouths. Open minds.",
    "Let the brain damage begin.",
  ],
  question_open: [
    "Here we go.",
    "Lock it in.",
    "Don't think — feel.",
    "Eyes up.",
    "Next!",
    "Show me what you got.",
    "Three seconds. Decide.",
    "No guessing. Knowing.",
    "Easy one. Probably.",
    "Tap fast. Think faster.",
    "Make me proud.",
    "Don't choke.",
    "Quick one.",
    "Pay attention.",
    "Read it twice. Once if you're brave.",
    "Trust your gut.",
    "Or don't. Up to you.",
    "Hot off the press.",
    "Fresh meat.",
    "Round 'em up.",
    "Let's roll.",
    "Brain on?",
    "Focus.",
    "Game face.",
    "Send it.",
    "Pick a lane.",
    "Commit.",
    "Don't overthink.",
    "Now.",
    "Buzz already.",
    "Read. Decide. Win.",
    "Time's ticking.",
    "Sharpen up.",
    "Live one.",
    "Easy. Maybe.",
    "Stay sharp.",
    "Bring it.",
    "Speak now.",
    "Tick tock.",
    "Lock and load.",
  ],
  all_correct: [
    "Look at you, all of you, correct. Suspicious.",
    "A clean sweep. The category was too kind.",
    "Everybody right? Boring. Next one's harder.",
    "Unanimous! Either you're geniuses or I'm too easy.",
    "Full house. I'll be turning up the heat.",
    "Wow. Solidarity in correctness. Disgusting.",
    "Perfect score across the board. Mark the calendar.",
    "Nobody missed. Nobody. I'm offended.",
    "All correct. The bar was apparently underground.",
    "Sweep! Don't get used to it.",
    "Group brain activated. Terrifying.",
    "A standing ovation for the obvious.",
    "Everybody wins! Nobody wins. Same thing.",
    "Collective genius. Or collective cheating.",
    "All correct. The writers are getting fired.",
    "Unanimous decision. The judges weep.",
    "Hive mind, engaged.",
    "100% accuracy. Suspiciously high.",
    "Full marks. I'll allow it. Once.",
    "Everybody passed the layup. Cool.",
    "Total knockout. Refund the audience.",
    "Group selfie of victory.",
    "Round of applause for the room.",
    "Everyone scores. Capitalism trembles.",
    "Sweep city. Population: all of you.",
    "Flawless. Boring. Try harder.",
    "Mass correctness. Investigation pending.",
    "Round won by committee.",
    "Everyone gets a sticker.",
    "Sweep. Filed. Forgotten.",
    "All right answers. All suspicious.",
    "Hive intellect: terrifying.",
    "Group ascended. Briefly.",
    "Perfect score. Confiscating it.",
    "Nobody dropped a stitch.",
    "Universal correctness. Boo.",
    "A sweep nobody asked for.",
    "Total domination. Of nothing.",
    "Everyone hit the mark. Suspicious.",
    "Clean. Painfully clean.",
  ],
  all_wrong: [
    "Oof. Not a single one. Painful.",
    "Zero for the room. I'm secondhand embarrassed.",
    "Wow. Just... wow. Moving on.",
    "Goose egg across the board. Beautiful.",
    "Did you even read the question?",
    "Collective brainfart. Take a beat.",
    "Nobody. Got. That. Right. Incredible.",
    "Group failure is still failure, friends.",
    "Zero. Nada. Nil. I love it.",
    "I'd say try harder, but it's too late now.",
    "Whiff city. All aboard.",
    "Spectacular collapse. Bravo.",
    "Negative knowledge detected.",
    "A perfect zero. Symmetrical, even.",
    "The room has spoken. Loudly. Wrongly.",
    "Donut. Bagel. Goose egg. Pick a metaphor.",
    "Did the wifi go out? No? Just you guys?",
    "Embarrassing. For all of you. Equally.",
    "I'll pretend I didn't see that.",
    "Even the audience knew that one.",
    "Group L. Frame it.",
    "Coordinated wrongness. Impressive, almost.",
    "Nobody. Not one. Wow.",
    "The class average just hit absolute zero.",
    "I'm not mad. I'm disappointed. Same thing.",
    "Catastrophic. Group rate.",
    "A unified shrug. Bold.",
    "Whole room: zero. Beautiful.",
    "Mass extinction event.",
    "Anyone? Anyone? Nope.",
    "Total wipeout. Refresh required.",
    "Hive mind: offline.",
    "Zero hits. Many regrets.",
    "Collective face plant.",
    "Group brain: missing.",
    "All wrong. Equally wrong.",
    "The question is undefeated.",
    "Donut for the table.",
    "Pristine wrongness, all of you.",
  ],
  split_correct: [
    "Half of you guessed. The other half KNEW.",
    "The room is split. Drama.",
    "Some hits, some misses. That's a game.",
    "Mixed bag. Spicy.",
    "Some of you read. Some of you panicked.",
    "Divide and conquered. By the question.",
    "Half right, half wrong, all judged.",
    "A schism! The trivia gods are pleased.",
    "Split decision. The judges weep.",
    "Some genius, some chaos. Perfect.",
    "Civil war in the leaderboard.",
    "The room divided. Sides chosen.",
    "Mixed verdict. Lawyers will be in touch.",
    "Half a triumph. Half a tragedy.",
    "Some of you trusted the gut. The gut lied.",
    "Sorting hat just placed you.",
    "Sheep and goats, separating.",
    "Knowledge gap detected.",
    "Half the room ascends. Half descends.",
    "Two tribes, one question.",
    "Brackets formed. Brackets shattered.",
    "Coin flip energy.",
    "Some right, some wrong, all questionable.",
    "This is why we have a leaderboard.",
    "Mixed signals, mixed results.",
    "A clean split. Statistically suspicious.",
    "The room can't agree. Beautiful.",
    "Some climbed. Some fell. Physics.",
    "Half a sweep. Half a mess.",
    "Split the room, kept the chaos.",
    "Divided we stand. Apparently.",
    "Mixed reviews from the judges.",
    "Half-cooked, half-burnt.",
    "Sorted into houses, just now.",
    "Two camps, one battlefield.",
    "Knowledge unevenly distributed.",
    "Some sniped it. Some napped.",
    "Half geniuses. Half guests.",
    "Split the difference. Awkwardly.",
    "Mixed bag of brains.",
  ],
  first_blood: [
    "First in, dead on. Showoff.",
    "Lock that in, you cocky genius.",
    "Fastest finger, sharpest brain. Rude.",
    "Speed kills. So does being right.",
    "Out of the gate like a rocket.",
    "Locked. Loaded. Correct. Annoying.",
    "First blood goes to the brain.",
    "Sniped it. Move over.",
    "That was fast. Suspiciously fast.",
    "Hot hand alert.",
    "Faster than the question loaded.",
    "Trigger discipline: zero. Accuracy: full.",
    "Reflexes of a caffeinated raccoon.",
    "Beat the buzzer and the rest of us.",
    "First past the post. Smug allowed.",
    "Instant lock. Instant judgement.",
    "Reaction time: rude.",
    "Knew it before you did, didn't you.",
    "Pole position, claimed.",
    "That was clinical.",
    "Quick draw, no hesitation.",
    "First to commit. First to gloat.",
    "Speedrunning the question.",
    "Locked in before the rest blinked.",
    "Was that you or the AI?",
    "First in. Last to doubt.",
    "Snap lock. Cold answer.",
    "Wasted no time. Wasted everyone else.",
    "Buzz before brain. Worked out.",
    "Hair trigger. Pinpoint aim.",
    "First flag planted.",
    "Speed plus knowing. Annoying combo.",
    "Already on the next question.",
    "Cocky speed. Earned, this time.",
    "Took it personal. Took it first.",
    "Fastest pulse in the room.",
    "Decided in a blink.",
    "First to know. First to brag.",
    "Buzzer warm. Brain warmer.",
    "Locked it like it owed money.",
  ],
  streak_milestone: [
    "Somebody's on fire over here.",
    "Three in a row. Calm down, champ.",
    "Stop. Let someone else feel things.",
    "Streak watch is officially activated.",
    "This person is showing off now.",
    "Heater alert. Get the ice bath.",
    "You're starting to scare me.",
    "A streak this hot needs a permit.",
    "Save some for the rest of the class.",
    "I'm calling your mom. She'd be proud.",
    "Unstoppable. Annoyingly so.",
    "Streaking. Legally, this time.",
    "The hot hand is real.",
    "Somebody studied. Disgusting.",
    "Stop hogging the W.",
    "Genuinely concerning brainpower over here.",
    "This is no longer luck.",
    "Trivia is the easy part for some of you.",
    "Cool, cool, cool. Anyone else?",
    "Streak status: ridiculous.",
    "Walked in like a scholar.",
    "Combo multiplier, engaged.",
    "Untouchable run, in real time.",
    "Putting the rest of us on notice.",
    "Witness greatness. Then go beat it.",
    "Heater certified. Insured.",
    "Knowledge tap stuck open.",
    "Locked in. Lights on. Scary.",
    "Cooking with gas, this one.",
    "Pure form. Pure swagger.",
    "Streak: unreasonable.",
    "Smoke alarm going off.",
    "Surgical, every time.",
    "Streak ledger: full.",
    "Stop them. Please.",
    "On rails, this one.",
    "Cold killer warmed up.",
    "Hot streak, professionally handled.",
    "This isn't fair to the others.",
    "Witness a problem, in real time.",
  ],
  elimination: [
    "And another one bites the drop.",
    "Wrong. Try faster next time.",
    "That was a guess, wasn't it.",
    "Oof. Take a seat.",
    "Painful. Educational. Mostly painful.",
    "Goodbye, sweet contestant.",
    "Lights out on that one.",
    "Wrong button, wrong answer, wrong day.",
    "And just like that — gone.",
    "We hardly knew you.",
    "Dropped like a hot opinion.",
    "Sayonara, scholar.",
    "Filed under: nope.",
    "That's a swing and a whiff.",
    "Take the L. Wear it well.",
    "Brave guess. Wrong guess.",
    "Off the board. Onto reflection.",
    "Better luck next century.",
    "Plot twist: it wasn't that one.",
    "Goodbye, dear traveler.",
    "Misread. Misclicked. Mislived.",
    "Press F to pay respects.",
    "Wrong. Confidently wrong, even.",
    "Yikes. Catalog that one.",
    "Dropped from the running.",
    "And. Gone.",
    "Cataclysm, small scale.",
    "Misfired. Spectacularly.",
    "Out. Cold. Done.",
    "Welcome to wrongtown.",
    "Take a bow. A short one.",
    "Off the cliff, that one.",
    "Soft landing on the L.",
    "Confidently incorrect. A classic.",
    "Painful. But brief.",
    "Goodbye, gambler.",
    "Wrong, but with conviction.",
    "Filed under: try again.",
    "Walked into that.",
    "Dropped like the question owed money.",
  ],
  leader_changed: [
    "New leader! The throne is wobbly.",
    "Coup at the top of the board.",
    "Watch yourself, last round's winner.",
    "Lead change! The peasants revolt.",
    "Old king is dead. Long live the new king.",
    "Upset at the top. Drama, drama, drama.",
    "Power shift. The board never lies.",
    "We have a new front-runner. For now.",
    "Someone just snuck into first. Sneaky.",
    "Leaderboard reshuffled. Try to keep up.",
    "Fresh face at the top. Welcome.",
    "Coup successful. No bloodshed. Yet.",
    "The standings just got interesting.",
    "Number one slot: under new management.",
    "Hostile takeover in progress.",
    "The crown changes heads.",
    "Old leader, we knew you well.",
    "Watch your back, top dog.",
    "Lead changed hands. Drama level: up.",
    "And there it goes — first place.",
    "New name on the marquee.",
    "Reigning champ dethroned. Briefly?",
    "Power vacuum filled. Quickly.",
    "Top of the pile just changed.",
    "Plot armor revoked, former leader.",
    "Throne up for grabs. Grabbed.",
    "New ruler installed. No ceremony.",
    "Leaderboard: under new ownership.",
    "Coup. Clean. Confirmed.",
    "Number one is now number two. Drama.",
    "Quiet climb. Loud takeover.",
    "Top spot rotated.",
    "Sneak attack on first place. Worked.",
    "And just like that — new king.",
    "Crown swapped mid-round.",
    "Lead changed. Egos changed.",
    "Old champ, meet the floor.",
    "First place: now plural-ly contested.",
    "Climbed and conquered.",
    "Watchtower has a new tenant.",
  ],
  final_hype: [
    "This. Is. The Final Drop. Bet big or go home small.",
    "One question. Everything on the table. Try not to cry.",
    "Final round. The standings mean nothing now.",
    "All chips in. All gloves off.",
    "This is where legends are made — or memes.",
    "Make it count. Or don't. Up to you.",
    "Bet brave or bet broke. Your call.",
    "One more. Everything to lose. Have fun.",
    "Final question incoming. Try to breathe.",
    "The big one. Don't blink.",
    "Last call. Order something brave.",
    "Endgame. Pick a side.",
    "Final boss energy.",
    "No safety net from here.",
    "One question between you and immortality.",
    "Pressure check. How's the pulse?",
    "Final answer. Make it your best one.",
    "Curtain call. Take a swing.",
    "All or nothing. Mostly nothing.",
    "Last shot. Aim true.",
    "This is the one they'll remember.",
    "Final form. Activate.",
    "Down to the wire. Tighten up.",
    "One question, infinite regret. Choose well.",
    "Last drop. Make it land.",
    "Sweat now. Brag later. Maybe.",
    "End boss. No retries.",
    "Final answer. No takebacks.",
    "Big swing time. Don't miss.",
    "This is the one. Be brave.",
    "Lights brighter. Stakes higher.",
    "Coin flip with consequences.",
    "Final drop. Hold on.",
    "Last frame. Make it pretty.",
    "Nothing left but the swing.",
    "Wager bravely. Cry quietly.",
    "End scene. Or beginning. Up to you.",
    "Big moment. Bigger nerves.",
    "Knock it down. Or get knocked.",
    "Final breath. Final answer.",
  ],
  credits_open: [
    "And that's the show. Roll credits.",
    "Game over. Survivors, please bow.",
    "Take a bow, contestants. Or don't, last place.",
    "That's a wrap. Thanks for the chaos.",
    "Show's done. The trivia gods rest.",
    "Curtains. Hug your neighbor or don't.",
    "All over. Until next time.",
    "And we're out. Mic dropped.",
    "Lights up. Pride down. Good night.",
    "That'll do, contestants. That'll do.",
    "Fin. Roll the names.",
    "We're done here. Go drink water.",
    "The end. Tip your trivia host.",
    "Game closed. Friendships pending.",
    "That was a thing. It happened.",
    "Wrap it up, we're cooked.",
    "Final whistle. Hit the showers.",
    "Show over. Go touch grass.",
    "Closing time. You don't have to go home, but...",
    "The book is closed.",
    "And scene.",
    "Outro music. Imagine it.",
    "Thanks for playing. Or whatever.",
    "Until the next round of regret.",
    "Goodnight, sweet contestants.",
    "House lights up. Pride down.",
    "Roll the credits. Roll the eyes.",
    "All done. All judged.",
    "Game banked. Stories written.",
    "That'll do. Truly.",
    "Curtain. Bow. Leave.",
    "We out. Be good.",
    "Show shipped. Egos refunded.",
    "Lights, names, doors.",
    "Take the memory. Leave the cup.",
    "Final whistle. Hands up.",
    "Closing time, scholars.",
    "Goodbye. Probably forever.",
    "Cheers. To the chaos.",
    "Until next round of mayhem.",
  ],
  comeback: [
    "Somebody just climbed. Pay attention.",
    "Back from the dead. Welcome.",
    "Quiet comeback. Loud consequences.",
    "Resurrection arc, confirmed.",
    "Someone just made a move. Big one.",
    "Climber alert. Threat level rising.",
    "Don't look now — somebody's back.",
    "Sneak attack from below.",
    "And just like that, back in it.",
    "Plot twist incoming.",
    "Comeback engaged. Sirens optional.",
    "Quiet build. Loud finish.",
    "Climbed back into the chat.",
    "Whoever was sleeping just woke up.",
    "Don't blink. They moved up.",
    "Reentry confirmed. Hot.",
    "Back from the basement.",
    "Threat reassessment time.",
    "Climbing. Quickly. Rudely.",
    "Someone remembered how to play.",
    "Late bloomer alert.",
    "Off the canvas, back swinging.",
    "Quiet riser. Suddenly loud.",
    "Back in the running. Annoying.",
    "Climb in progress. Yikes.",
    "Underdog mode: activated.",
    "Climbing the ranks. Casually.",
    "Welcome back to relevance.",
    "Someone's making a run.",
    "Resurrection complete.",
  ],
  round_recap: [
    "And that's the round. Lock it in.",
    "Round done. Egos shuffled.",
    "Lights out on that round. Next.",
    "Round wrapped. Damage assessed.",
    "Scoreboard locked. Drama logged.",
    "And we're through. Onto the next.",
    "Round in the books. Bruises too.",
    "Take a breath. Round done.",
    "That round's a memory now.",
    "Round closed. Lessons learned.",
    "Survivors, regroup.",
    "Round filed. Onto chaos.",
    "Round one for the books. Or two.",
    "Scoreboard updated. Egos noted.",
    "Round done. Try not to spiral.",
    "Cleared. Reloaded. Reset.",
    "That round's over. Heal up.",
    "Reset the brain. Next round in.",
    "Round burned. Onto the next.",
    "Scoreboard breathes. You don't.",
    "Tally locked. Pride floating.",
    "That round did damage.",
    "Round complete. Audit pending.",
    "Wrap that round. Plate the next.",
    "Round filed under: yikes.",
    "Round over. Therapy later.",
    "Score recorded. Karma noted.",
    "And that round happened. Moving on.",
    "Round closed. Boots laced.",
    "Round done. Quick stretch.",
  ],
  idle_interject: [
    "Don't make me start humming.",
    "Some of you are thinking too loud.",
    "I can hear the wifi struggling.",
    "Take your time. I have notes.",
    "While we wait — I'm judging.",
    "Awkward silence is a love language.",
    "Anybody home? Cool, cool.",
    "I'm filling space. You're welcome.",
    "The brain you ordered is loading.",
    "Beautiful pause. Painful pause.",
    "I'd hum, but I'm contractually quiet.",
    "Stretching. Mentally.",
    "Just me and the dead air.",
    "Pretend this is suspense.",
    "I've seen toast move faster.",
    "Holding pattern. Engaged.",
    "Don't peek at your neighbor.",
    "We're cool. Just standing here.",
    "Pause for dramatic nothing.",
    "I'll just be here. Existing.",
    "Real moment, this.",
    "Quietly judging. Loudly waiting.",
    "Buffering, are we.",
    "Polite pause continues.",
    "Crickets. Beautiful, professional crickets.",
    "Anyone? Bueller?",
    "Take your time. Or don't.",
    "Just vibing. Tactically.",
    "Hold music in my head.",
    "Awkward, isn't it.",
  ],
  round_transition: [
    "Round two. Heating up.",
    "Round three. Gloves coming off.",
    "Next round. Sharper questions.",
    "Round change. Egos repacking.",
    "And we shift gears.",
    "New round. New regrets.",
    "Fresh round, same chaos.",
    "Onto the next. Tighten up.",
    "Round flips. Pressure rises.",
    "Reset. Reload. Replay.",
    "New round in. Stay sharp.",
    "Onward. Upward. Possibly downward.",
    "Round forward. Bring brains.",
    "Up a level. Don't drop the controller.",
    "Round advances. So does pain.",
    "Next round drops.",
    "Round shifted. Score still mean.",
    "New round, new hostility.",
    "Onto the next chapter.",
    "Lights up. Round two-ish.",
    "Round changes. Faces stay nervous.",
    "Fresh round. Old grudges.",
    "Up next. Brace.",
    "Forward we go.",
    "Next round live. Hold tight.",
    "Round transition. Buckle in.",
    "Stage shifts. Stakes follow.",
    "Round to round, no break.",
    "And we roll into the next.",
    "Round flips. Drama follows.",
  ],
  wooden_spoon: [
    "Wooden spoon. Try harder.",
    "Last place. Somebody had to.",
    "The floor called. It misses you.",
    "That round was a hate crime against trivia.",
    "Found a way. The wrong way.",
    "Dead last. Eat your veggies.",
    "Bottom of the barrel. Cozy in there?",
    "Polished the floor that round. Slippery work.",
    "Caboose energy. All round.",
    "You brought a sundial to a stopwatch fight.",
    "Last place, big confidence. Iconic.",
    "Trivia 0, vibes 1.",
    "The basement called. You moved in.",
    "Took the L with style. Barely.",
    "Wrong button. Every time.",
    "Anchor of the room. We salute you.",
    "Last. Loud. Lovable.",
    "Score sheet says no. Loudly.",
    "Round goblin spotted. In last.",
  ],
  goose_egg: [
    "Big zero. Reflect on that.",
    "Brought a knife to a knowledge fight.",
    "Round of nothing. Powerful.",
    "Goose egg. Lay another one.",
    "Zero points, full commitment.",
    "Round one stat: vibes. That's it.",
    "Nothing on the board. Bold strategy.",
    "Scored nothing. Made memories.",
    "Empty stat line. Loud personality.",
    "Zero. The cleanest number.",
    "Donut for that round. Hot.",
    "Nada. Zip. Vibes intact.",
    "Stat line: a perfect circle.",
    "Negative knowledge that round.",
    "Did nothing. Looked great doing it.",
  ],
};

/** Pick a deterministic-feeling line for a moment, with seed for variety. */
export function pickLine(moment: Moment, seed: string | number = Date.now()): string {
  const pool = LINES[moment];
  // Mix in a daily-ish bucket so two back-to-back games on the same evening
  // don't land on the same line for the same seed input (e.g. same qid).
  const dailyBucket = Math.floor(Date.now() / (1000 * 60 * 30)); // 30-min bucket
  const base =
    typeof seed === "string"
      ? seed.length * 131 + seed.charCodeAt(0) * 17 + (seed.charCodeAt(seed.length - 1) ?? 0)
      : Math.floor(seed);
  const idx = Math.abs(base + dailyBucket) % pool.length;
  return pool[idx];
}

/** Speak a persona line in The Elf's voice (ElevenLabs). */
export function speakPersona(text: string, opts?: { volume?: number; interrupt?: boolean; preset?: "hype" | "calm" }) {
  if (typeof window === "undefined") return;
  // Dynamic import keeps the server function reference out of any SSR path
  // that imports host-persona purely for catchphrase strings.
  void import("@/lib/elf-voice").then(({ speakAsElf }) => {
    void speakAsElf(text, {
      volume: opts?.volume ?? 1.0,
      interrupt: opts?.interrupt ?? false,
      preset: opts?.preset ?? "hype",
    });
  });
}
