// Extra persona lines. Merged into LINES at import time in host-persona.ts.
// Adding lines here automatically expands the pre-baked persona pack the
// admin baker generates, so we can use up ElevenLabs credits without
// touching player-facing code paths.

type Moment =
  | "intro_hype"
  | "question_open"
  | "all_correct"
  | "all_wrong"
  | "split_correct"
  | "first_blood"
  | "streak_milestone"
  | "elimination"
  | "leader_changed"
  | "final_hype"
  | "credits_open"
  | "comeback"
  | "round_recap"
  | "wooden_spoon"
  | "goose_egg"
  | "idle_interject"
  | "round_transition"
  | "last_to_lock"
  | "random_jab";

export const EXTRA_LINES: Record<Moment, string[]> = {
  intro_hype: [
    "Doors sealed. Timer armed. Egos exposed.",
    "You paid attention in third grade? Prove it.",
    "Everyone's a genius until the buzzer starts.",
    "Warm up your excuses. You'll need them.",
    "Confidence is a currency. Spend wisely.",
    "The couch is not a study aid. Regretful discovery incoming.",
    "Fresh brains, fresh bruises. Standard show.",
    "I brought questions. You brought vibes. Uneven trade.",
    "Round zero: pretend you're smart. Round one: get exposed.",
    "Warmups are for cowards. Straight into the meat.",
    "If you googled the topic, congratulations, still not enough.",
    "Someone here peaks in ten seconds. Someone else never does.",
    "Big-brain energy or bust. Bust likely.",
    "Trivia stretches: raise eyebrows, lower expectations.",
    "Confidence check: how loud is that inner voice? Good, we'll break it.",
    "Round one is a mirror. Some of you won't like it.",
    "You've been trained your whole life for this. Barely.",
    "Chairs comfortable? Should be. You'll be sitting a while.",
    "Warmed up? Same. Let's cook.",
    "Trivia laws apply. Cheating laws also apply. Barely.",
    "Sharpen your instincts. Blunt your ego.",
    "Guessing is a strategy. A losing one, but still.",
    "Enter humble. Leave humbled. Consistent brand.",
    "The buzzer doesn't care about your feelings.",
    "Some of you will surprise yourselves. The rest will confirm suspicions.",
    "Big talk stage left. Small results stage right.",
    "The lights are hot. So is the shame.",
  ],
  question_open: [
    "Read fast, decide faster.",
    "Trust the first instinct.",
    "No second guesses.",
    "Snap it up.",
    "Answer's right there.",
    "Or is it.",
    "Clock's judging you.",
    "Decide already.",
    "This one's mean.",
    "Commit or die.",
    "Look sharp.",
    "Move.",
    "Ticking.",
    "Locked in?",
    "Answer looks close.",
    "Or does it.",
    "Confidence check.",
    "Bet on yourself.",
    "One shot.",
    "Quick brain, please.",
    "Wake up.",
    "Snap decision.",
    "Read carefully.",
    "Or don't.",
    "Feel it.",
    "Timer moves.",
    "So should you.",
  ],
  all_correct: [
    "Unified genius. Suspicious.",
    "Everyone's right. The category owes me an apology.",
    "Clean board. Boring board.",
    "Group won. Individually meaningless.",
    "Total sweep. Feels wrong.",
    "Perfect room. Imperfect writer.",
    "You all cheated. Nobody argues.",
    "Consensus achieved. Trivia weeps.",
    "Every tile lit. Nothing to see.",
    "Universal correctness. Report to HR.",
    "Sweep. Suspicious sweep. Filed sweep.",
    "Full board. Zero drama.",
    "Group hit. Group flat.",
    "Everyone right. Nobody special.",
    "Sweep noted. Difficulty rising.",
    "You all know this. Fine.",
    "Perfect. Predictable.",
    "Room clean. Ego dirty.",
    "Universal W. Universally boring.",
    "Everyone got it. Alarming.",
  ],
  all_wrong: [
    "Room-wide whiff. Historic.",
    "Zero correct. Perfectly wrong.",
    "Full plate of failure. Chef's kiss.",
    "Group L. Framed and hung.",
    "Nobody. Really? Nobody?",
    "Wrong across the board. Consistent.",
    "Every tile wrong. Almost artful.",
    "Room went for chaos. Chaos delivered.",
    "Perfect zero. Frame it.",
    "You collectively agreed to be wrong. Bold.",
    "Nothing correct. Nothing salvageable.",
    "Zero out of many. Poetic.",
    "You all guessed. All wrong.",
    "Consensus wrongness. Impressive.",
    "Room brain: closed.",
    "Total whiff. Sponsor us.",
    "Full room of nope.",
    "Combined intelligence: negative.",
    "That question won.",
    "Question one. Room zero.",
  ],
  split_correct: [
    "Room split. Standings shift.",
    "Half brains. Half prayers.",
    "Sharp and shaky both showed up.",
    "Some knew. Some winged it. Some napped.",
    "Split verdict. Sorted, briefly.",
    "Divided room. Delighted host.",
    "Some correct, some coping.",
    "Split lines drawn.",
    "Sorted the sharp from the sheepish.",
    "Half a win. Half a plea.",
    "Split decision. Fair enough.",
    "Some right. Some regretful.",
    "Room fractured. Politely.",
    "Sorted mid-flight.",
    "Half genius. Half improv.",
    "Split neatly. Painfully.",
    "Two rooms in one.",
    "Sorted. Filed. Judged.",
    "Some ate. Some fumbled.",
    "Split confirms rankings.",
  ],
  first_blood: [
    "Straight to the button. No thinking.",
    "First to the trigger. First to the throne.",
    "Someone rehearsed this.",
    "Snap answer. Snap correct.",
    "First blood, drawn quick.",
    "Fast hands. Right mind.",
    "Speed plus knowing. Illegal.",
    "First and correct. Rude combo.",
    "Someone's caffeinated and educated.",
    "Reflex genius spotted.",
    "Locked before the rest read.",
    "That was quick. Correctly quick.",
    "First across. Cocky landing.",
    "Straight in, no hesitation.",
    "Trigger discipline: zero. Accuracy: unfair.",
    "Fastest brain in the room.",
    "First out the gate. First to gloat.",
    "That was surgical.",
    "First to lock. First to smirk.",
    "Sniped it clean.",
  ],
  streak_milestone: [
    "Streak alive and mean.",
    "Heater sustained.",
    "This one's on rails.",
    "Combo climbing.",
    "Streak: alarming.",
    "Cooking hot. Cooking clean.",
    "Streak: professional.",
    "On a run. Rude one.",
    "Streak count says something. It says: menace.",
    "Streak stat: threatening.",
    "Locked-in mode: engaged.",
    "Streaking with confidence.",
    "Combo says get out of the way.",
    "Streak alarm sounding.",
    "Heat check passed.",
    "Streak status: dangerous.",
    "Somebody found the flow.",
    "Streak: unpolite.",
    "Combo unbroken. Room shaken.",
    "Streak growing. Room shrinking.",
  ],
  elimination: [
    "Dropped, tagged, filed.",
    "Off the tile. Onto reflection.",
    "Wrong click. Right regret.",
    "Off. Cold. Filed.",
    "That's an out.",
    "Tapped the wrong lane.",
    "Dropped hard. Landed loud.",
    "Off the board. Onto the couch.",
    "That answer lied to you.",
    "Wrong tile. Right pain.",
    "Off the tour. Off the trip.",
    "Trapdoor engaged.",
    "Went for it. Missed.",
    "Wrong. Loud. Filed.",
    "Big swing. Big miss.",
    "Off the board with style.",
    "Confident wrongness. Loud farewell.",
    "That was courageous. And wrong.",
    "Off. Done. Sorted.",
    "Dropped. Applause is optional.",
  ],
  leader_changed: [
    "New top. Old grudges.",
    "Board flipped. Faces flipped.",
    "New name up top. Adjust.",
    "Coup logged. Peaceful.",
    "Fresh number one. Same drama.",
    "Top slot rotated.",
    "Reigning champ down a step.",
    "Board reshuffled.",
    "New face on the marquee.",
    "Old king benched.",
    "Sneaky climb. Loud landing.",
    "Top spot changed hands. Politely.",
    "Number one is a new one.",
    "Leaderboard has a new dictator.",
    "Standing swap. Ego swap.",
    "Fresh face on top. Fresh fear below.",
    "Board updated. Egos updated.",
    "Top spot: under new management.",
    "Leader dethroned. Quickly.",
    "Coup complete. Bloodless.",
  ],
  final_hype: [
    "Final question. Final regret.",
    "Wager brave. Cry proud.",
    "One left. Make it huge.",
    "This is the shot.",
    "Big swing time.",
    "Last drop. Best answer.",
    "One question. All chips.",
    "Wager it all or wager nothing. Both are personalities.",
    "This is the memorable one.",
    "End boss active.",
    "Final call. Big or bust.",
    "One question. Whole show.",
    "Do the brave thing.",
    "Last swing. Aim true.",
    "Final drop. Final answer.",
    "Bet everything. Or bet dignity.",
    "One shot. Loud shot.",
    "Final decision. Final memory.",
    "Big finish incoming.",
    "This one lasts forever.",
  ],
  credits_open: [
    "Show shipped. Egos itemized.",
    "That's a wrap. Truly.",
    "Cameras cool. Trophies warm.",
    "House lights up.",
    "Curtain, final.",
    "Trivia banked. Regrets filed.",
    "Roll credits. Roll shoulders.",
    "Show's done. Drive safe.",
    "That was that. Filed under: fun.",
    "Curtain down. Group chat up.",
    "Show closed. Debates open.",
    "Names roll. Memories linger.",
    "That's the whole game.",
    "Trophy handed. Egos returned.",
    "Show wrapped. Refunds denied.",
    "Show over. Argue gently.",
    "That's a full show.",
    "Cameras off. Feelings on.",
    "Rolling names. Rolling eyes.",
    "That's the whole thing.",
  ],
  comeback: [
    "Comeback confirmed.",
    "Off the mat. Onto the podium.",
    "Sneak riser spotted.",
    "Climb noticed. Threat rising.",
    "Underdog waking up.",
    "Basement dweller ascending.",
    "Sleeper woke.",
    "Recovery in progress.",
    "Back in the mix.",
    "Climbing rudely.",
    "Late bloomer, big bloom.",
    "Quiet climb, loud impact.",
    "Comeback engaged.",
    "Rejoined the fight.",
    "Off the floor, onto the board.",
    "Climb ongoing. Sirens optional.",
  ],
  round_recap: [
    "Round burned. Onward.",
    "Round shelved.",
    "Round filed. Boots relaced.",
    "Round done. Next.",
    "Round done. Regroup.",
    "Round closed. Wounds counted.",
    "Round processed. Ego pending.",
    "Round wrapped. Bruises noted.",
    "Round complete. Report submitted.",
    "Round tallied. Onward.",
    "Round tucked in.",
    "Round complete. Deep breath.",
    "Round shipped. Next round loading.",
    "Round packaged. Sent.",
    "Round put to bed.",
  ],
  wooden_spoon: [
    "Wooden spoon polished.",
    "Basement rented. Long lease.",
    "Bottom of the pile. Cozy?",
    "Anchor position claimed.",
    "Last, but proud.",
    "Floor is yours.",
    "Anchor of the round.",
    "Bottom slot booked.",
    "Cellar dweller crowned.",
    "Wooden spoon issued.",
    "Room's caboose.",
    "Basement king.",
    "Bottom of the standings, top of the excuses.",
    "The floor called. You answered.",
  ],
  goose_egg: [
    "Big zero. Loud zero.",
    "Round score: pure zen.",
    "Donut delivered.",
    "Nothing scored. Everything felt.",
    "Zero, but committed.",
    "Perfect nothing.",
    "Donut framed.",
    "Round score: negative vibes.",
    "Zero points, big presence.",
    "Empty stat, full character.",
    "Round total: dignity only.",
    "Zero. With flair.",
  ],
  idle_interject: [
    "Any second now.",
    "The silence is doing all the work.",
    "I'll keep waiting. Loudly.",
    "Real dramatic pause, this.",
    "Take your time. Or don't.",
    "Standby engaged.",
    "Holding. Loudly.",
    "Dead air continues.",
    "Time is passing. Rudely.",
    "Awkward beats. On beat.",
    "I'll wait. My contract says so.",
    "Silence noted. Judged.",
    "Any thoughts? Anyone?",
    "This pause is professional.",
    "I've stopped aging. Convenient.",
    "Buffering hearts and minds.",
    "Just vibes. Just standing.",
    "Take a breath. Ok, now go.",
    "Longest pause on record.",
    "Timer says: soon.",
  ],
  round_transition: [
    "Round shifts. Egos jitter.",
    "Round flips. Brains adjust.",
    "Round change. New wounds.",
    "Round rolls. Onward.",
    "Round moved. Chairs shifted.",
    "Round pivots.",
    "Round advances. So does danger.",
    "Round transitions. Nerves too.",
    "Round flip. Deep breath.",
    "Round hands off.",
    "New round. New mistakes.",
    "Round change. Same show.",
    "New chapter. Same book.",
    "Round shifts, drama holds.",
    "Round change. Standings breathe.",
  ],
  last_to_lock: [
    "Late lock. Legal lock.",
    "Squeaked in.",
    "Last across. Barely.",
    "Right on the wire.",
    "Late but locked.",
    "By a whisker.",
    "Buzzer kiss. Legal.",
    "Late lock, clean.",
    "Slid in on the horn.",
    "Cutting it thin. Living dangerously.",
    "Waited. Then locked. Nice pulse.",
    "Down to the wire and past.",
  ],
  random_jab: [
    "Still here. Barely.",
    "Silent competitor spotted.",
    "Quiet corner detected.",
    "Sneaky player mode.",
    "Lurking. Judging. Vibing.",
    "Present, if not accounted for.",
    "Ghost in the room.",
    "Silent scorer, silent story.",
    "Background character noted.",
    "Vibes strong. Score TBD.",
    "Wallflower with intent.",
    "Not saying much. Not doing much.",
    "Lurking with intent.",
  ],
};
