// Sasha — the sultry adult-mode female co-host. She interjects ~12.5% of
// the time when adult mode is on, using ElevenLabs "Jessica" (a warm,
// confident, flirty voice). Content rules match the male adult pool:
// profanity + innuendo yes, no slurs, no minors, no real-person targeting,
// nothing non-consensual.

type Moment =
  | "intro_hype"
  | "question_open"
  | "all_correct"
  | "all_wrong"
  | "split_correct"
  | "first_blood"
  | "streak_milestone"
  | "elimination"
  | "leader_changed"
  | "final_hype"
  | "credits_open"
  | "comeback"
  | "round_recap"
  | "wooden_spoon"
  | "goose_egg"
  | "idle_interject"
  | "round_transition"
  | "last_to_lock"
  | "random_jab";

/** Male-coded names Sasha will flirt with when she hits a {flirtGuyName} line.
 *  Kept short so the bake stays bounded — every flirty line multiplies by
 *  this list at bake time (server) and gets randomly substituted at pick
 *  time (client). Cache lookup matches the resolved string. */
export const ADULT_FLIRT_GUY_NAMES: string[] = [
  "Chad",
  "Tyler",
  "Josh",
  "Brad",
  "Kyle",
  "Ryan",
  "Jake",
  "Cody",
  "Trevor",
  "Dylan",
  "Mason",
  "Blake",
  "Connor",
  "Logan",
  "Hunter",
];

export const LINES_SASHA_ADULT: Partial<Record<Moment, string[]>> = {
  intro_hype: [
    "Mmm, hi boys. Somebody said trivia and I came running.",
    "Well well well. Look at this lineup. I'm gonna have fun with you tonight.",
    "Ladies, gentlemen, and whatever {flirtGuyName} is — welcome.",
    "I hope you brought your A-game and your best cologne. Both matter.",
    "Alright cuties, don't disappoint me. It's a bad look.",
    "Warm up those brains, boys. And whatever else you've got.",
    "Oh, {flirtGuyName}, I've been thinking about you since check-in. Focus up.",
    "I'll be popping in when it gets spicy. Try to keep up.",
    "Sasha's here. That means somebody's about to blush. Probably {flirtGuyName}.",
    "You brought your friends. Cute. I brought my judgment. Cuter.",
    "Alright players. Let's see who's got brains and who's just got shoulders.",
    "Ohhh, this is a fun crowd. Somebody's leaving with a story tonight.",
    "Let's play, boys. Bring me something impressive.",
    "Hi {flirtGuyName}. Don't choke. I'll be watching.",
    "Trivia and me — what a night for you all.",
    "Sasha's on the mic. Behave, if you must.",
    "I have a soft spot for confident wrong answers. Somebody deliver.",
    "Boys — and I use that word affectionately — let's begin.",
    "Get your minds right. I like a player with focus.",
    "Alright cuties, buzz in like you mean it.",
  ],
  first_blood: [
    "Ooh, {flirtGuyName}, first in. Confident. I like it.",
    "First blood! Somebody's showing off for the girl on the mic.",
    "That was FAST, {flirtGuyName}. Is speed a thing with you?",
    "Look at that trigger finger. Somebody's been practicing.",
    "First lock. That was hot. Do it again.",
    "First blood from {flirtGuyName}. Somebody call HR, that was aggressive.",
    "Oh, {flirtGuyName}, easy tiger. Save some energy for later.",
    "That was clean, cocky, and correct. My three favorite Cs.",
    "First in! I love a decisive man.",
    "You buzzed in like you had something to prove. Prove more.",
    "Locked in like you own the place. Do you?",
    "First blood is loud blood. Keep talking, sugar.",
    "That reflex? Illegal. And sexy.",
    "Somebody in the room is flexing. I noticed. Everyone noticed.",
    "Fastest finger in the lobby. I'll allow it.",
    "First lock, {flirtGuyName}. Now hold it — nervously — like a first date.",
    "Look at you. First in. Confident. Doomed. Beautiful.",
    "The buzzer never stood a chance. Bless your fingers.",
    "First correct. First to catch my attention.",
    "That was quick. Suspiciously quick. Are you a cheater or a genius, {flirtGuyName}?",
    "Fast lock. Faster ego. I'm here for it.",
    "Locked, loaded, gloating. My kind of player.",
    "You just made the rest of the room look slow. Good.",
    "First blood. Now buy yourself a drink. You've earned it.",
    "{flirtGuyName}, that was hot. Try not to peak.",
  ],
  streak_milestone: [
    "Oh, {flirtGuyName}. Look at you on a streak. Cocky little thing.",
    "That's three, sugar. Any more and I might swoon.",
    "Streak alert. Somebody's showing off. And I'm watching.",
    "Unstoppable. Somebody pour this genius a drink.",
    "That brain, {flirtGuyName}. That BRAIN.",
    "You're on fire and I'm here for it. Keep going.",
    "Streak from {flirtGuyName}. I'm impressed. Rare compliment.",
    "That's four in a row. Big brain, bigger ego. Combo.",
    "Cooking. With attitude. Please continue.",
    "Sustained excellence. Rare. Sexy.",
    "You've got a rhythm going. Don't let anyone break it.",
    "That's a streak, honey. Everyone else, weep.",
    "In the zone. Deep in it. I'll be down here waiting when you resurface.",
    "Somebody's showing off. Keep going. Please.",
    "Streak city. Population: you. And me, watching.",
    "Every answer, correct. Every buzz, first. What a night for {flirtGuyName}.",
    "You're on a roll. It's making the rest of them cranky. Delicious.",
    "That's the third correct in a row. I'm officially rooting for you.",
    "Streak locked. Confidence unhinged. Perfect.",
    "The board is bending to your will. Sexy.",
    "Cook, sugar. Cook.",
    "That streak has main character energy.",
    "Everyone stop. Watch this one. This is what talent looks like.",
    "Somebody's gonna be really full of themselves after this. Beautiful.",
    "That's the streak of the night. Contender for MVP. And other things.",
  ],
  all_correct: [
    "Ooh, full sweep. I love a competent room.",
    "Everyone got it. Even {flirtGuyName}, and honey, that's a shock.",
    "Full house. Somebody buy a round. Preferably {flirtGuyName}.",
    "Clean board. My type of lobby.",
    "All correct. I'm proud. And a little turned on. Whatever.",
    "Full points, boys. Don't let it go to your heads. Too late.",
    "Every one of you. Rare. Impressive. Suspicious.",
    "Clean sweep. Cool. Do it again. I dare you.",
    "Everyone winning. I'm blushing. A little.",
    "Full lobby, full points. Sasha approves.",
  ],
  all_wrong: [
    "Not a single one? Oh, boys. Boys.",
    "The whole room whiffed. I'm equal parts amused and horrified.",
    "Zero for the lobby. Even {flirtGuyName}. Especially {flirtGuyName}.",
    "None of you? That's cute. In a sad way.",
    "You all just failed together. Bonding activity.",
    "The correct answer was RIGHT THERE, boys.",
    "Group L. I'll be right back, I need a drink.",
    "Everyone wrong. My disappointment is measurable.",
    "That was a war crime, boys.",
    "Nobody got it. Not one. I'm gonna assume you were all distracted.",
    "Universal wrong. Historic. Embarrassing. Delicious.",
    "All wrong. Confidence intact. Delusional. Beautiful.",
    "This is the group text I'd screenshot and send to my friends.",
    "Zero points across the room. Take a good long look at yourselves, boys.",
    "This is what happens when you don't listen to me.",
    "Y'all whiffed as a unit. Impressive coordination.",
    "The wrong answers were louder than the right one. There wasn't one.",
    "Everyone. Wrong. Together. Iconic.",
    "That was the trivia equivalent of a group breakup. Painful.",
    "Nobody. Nobody at all. My god, boys.",
    "You all guessed the same wrong thing. That's teamwork!",
    "Zero. As in your combined effort. Charming.",
    "This is why I don't trust group projects.",
    "Not one of you. I'm putting this in my highlight reel.",
    "Boys. BOYS. Come on.",
    "Everyone missed. I'm mad but I love it.",
    "Full whiff from the entire lobby. That took skill.",
    "Historic failure. Group photo.",
    "Nobody got it. That's a first. And hopefully a last.",
    "That was so wrong I felt it in my earrings.",
  ],
  split_correct: [
    "Half of you nailed it. The other half — {flirtGuyName}, I saw that.",
    "Split verdict. Come sit on my side of the room, {flirtGuyName}.",
    "Some smart. Some hopeful. Same crowd every week.",
    "Half right. Half in trouble. Same energy.",
    "Mixed bag, boys. As always.",
    "Half correct, half in denial. My favorite ratio.",
    "The smart ones are gloating. The rest are pouting. Same difference.",
    "Split decision. Take a shot. Regroup.",
    "Half win, half whiff. Perfect chaos.",
    "Some of you eating good. The rest of you? Snack later.",
    "Half of you get to talk shit. The rest get to sit.",
    "Split. Awkward. Very public. Very fun.",
    "Half winners, half babies. Deal.",
    "The smart half is gonna gloat. The dumb half deserves it.",
    "Divided lobby, divided respect. My kind of night.",
  ],
  elimination: [
    "Bye, sugar. That was a bold swing.",
    "Ohhh, {flirtGuyName}. I had such high hopes for you.",
    "Eliminated. Take a shot. Take a breath. Try again next time.",
    "Bye bye, cutie. See you at the after party.",
    "That's a rough exit, {flirtGuyName}. I'll comfort you later.",
    "Off the board. Onto the bench. It's a look.",
    "Eliminated with confidence. Which is somehow worse. Bless.",
    "Gone, {flirtGuyName}. And honestly, the room feels a little sadder.",
    "That was a swing and a big, sexy miss.",
    "Bye, love. Try to remember the good times.",
    "Eliminated. Please retrieve your ego at coat check.",
    "That guess had confidence. It had no basis. Iconic.",
    "Out. Like a light. And your dating stats.",
    "Off the board, {flirtGuyName}. Save me a seat at the bar.",
    "That was a bold wrong answer. Sasha respects the boldness. Not the wrong.",
    "Gone. Reduced. Simplified. Very embarrassing.",
    "Bye, big guy. Big swing, big miss.",
    "Elimination! And it's {flirtGuyName}. Predictable, but heartbreaking.",
    "Off the map. Off the plan. Off my radar.",
    "You went from contender to content in one answer. Progress.",
    "Bye, sugar. Come find me after the game. Or don't. I'm busy.",
    "Eliminated. Full stop. Beautiful sunset ending.",
    "That was quick. A little embarrassing. A lot entertaining.",
    "Gone. Somebody get this player a soft blanket and a nap.",
    "Booted, {flirtGuyName}. Take it with grace. Or don't. Either is fine.",
    "Oh honey. No. That's a no.",
    "Eliminated. Take a shot. It's medicinal.",
    "Bye. Don't slam the door. Actually, do. Make it dramatic.",
    "Gone like a bad decision. Everyone has one.",
    "You just eliminated yourself in real time. Impressive.",
  ],
  leader_changed: [
    "New leader on the board. Somebody's about to get insufferable.",
    "The crown moved. {flirtGuyName}, don't get cocky. Actually, do.",
    "Fresh face on top. I love a plot twist.",
    "New number one! Everyone else, cope.",
    "Regime change! Long live whoever this is.",
    "Board flipped. Someone just got humbled in HD.",
    "New leader. Fresh insults incoming.",
    "The lead changed hands. Somebody's ego just imploded.",
    "New top dog. Loud. Deserving. Slightly hot.",
    "Coup at the top. Executed cleanly.",
    "Leaderboard drama. Sasha lives for this.",
    "New number one. Watch your back, honey.",
    "Fresh king (or queen) of the hill. Enjoy the view.",
    "The board just gentrified. Rents are up.",
    "The lead changed. So did the vibe.",
  ],
  final_hype: [
    "Final question. Deep breath, boys. Don't disappoint me.",
    "This is it. Everything on the line. Including {flirtGuyName}'s dignity.",
    "The final. Please, for me, don't choke.",
    "Big finish. Big pressure. Big fumble potential.",
    "Last question. Sasha's watching. No pressure.",
    "One shot. Take it clean. Take it hard.",
    "The finale. My favorite part.",
    "Last one. Impress me.",
    "Final answer. Bring the heat.",
    "This is where legends are born. Or embarrassed on international waters.",
    "One question left, boys. Give me a show.",
    "Big finish. I'm watching. Make it count.",
    "Final question. Try not to blow it. Save that for later.",
    "Last chance saloon. Order carefully, {flirtGuyName}.",
    "One shot. One guess. One winner. I love it.",
  ],
  credits_open: [
    "That's a wrap, boys. Text me. Or don't. Actually, do.",
    "Show's over. Somebody buy me a drink.",
    "Trivia's done. Real life's still real. Sorry, boys.",
    "Great game, cuties. See you next round.",
    "Credits are rolling. So am I. Home. Alone. Whatever.",
    "That's the show. Rate us five stars, boys.",
    "Sasha out. Miss me a little.",
    "Wrap it, rack it, remember the good parts.",
    "Signing off, cuties. Be safe. Or don't.",
    "Show done. Text me your regrets.",
    "That was fun. For me. Was it fun for {flirtGuyName}? Probably not.",
    "Game complete. Go home. Or come find the bar.",
    "See you at the next one, boys. Bring a better crew.",
    "That's the show. My work here is done. My drinking is not.",
    "Wrap. Cut. Print. Text me.",
    "Show's over. Somebody take {flirtGuyName} home before he cries.",
    "Alright cuties, get out. Sasha needs a nap.",
    "Roll credits. Roll to bed. Roll into your Sunday scaries.",
    "It's been a night. I'll see you again, hopefully.",
    "Bye, sugars. Don't do anything I wouldn't do. Which is a wide window.",
  ],
  comeback: [
    "Look who's back. {flirtGuyName}, that's a comeback and I'm impressed.",
    "Comeback alert! Sasha loves an underdog.",
    "That climb was aggressive. And a little hot.",
    "From the dead. Beautiful.",
    "Somebody found their groove. And I noticed.",
    "Comeback szn for {flirtGuyName}. Buckle up.",
    "That's a resurrection, honey.",
    "Rising like the volume on my playlist. Not so subtle.",
    "Big comeback, big energy. Big appeal.",
    "Underdog rising. Sasha's rooting for you.",
    "The board shifted. Somebody wants it.",
    "Comeback in progress. Trash talk enabled.",
    "You clawed your way back. That's the whole thing. Do it more.",
    "Watch out. This player is not done yet.",
    "That was a comeback with style, {flirtGuyName}. Get it.",
  ],
  round_recap: [
    "Round done. Boys, some of you need to sit down.",
    "That round chewed a few of you up. Delightful.",
    "Recap: some smart, some sad, all mine.",
    "Round done. Sasha's judgments are pending. Kidding — they're final.",
    "That was a round. Rankings are… interesting.",
    "Round wrapped. Some of you owe {flirtGuyName} an apology.",
    "That round was rough. I loved it.",
    "Recap time. Nobody looks great, honestly.",
    "Round closed. Boys, regroup and rally.",
    "That round taught us who cares and who's here for the drinks.",
  ],
  wooden_spoon: [
    "Last place. Honey. HONEY.",
    "Dead last. And confident? Confusing. Charming. Concerning.",
    "You're at the bottom, {flirtGuyName}. Cozy?",
    "Wooden spoon. Polished. Delivered. Awkwardly.",
    "Somebody had to lose. But this hard? Show off.",
    "Rock bottom energy. I like a project.",
    "You brought big loser energy. It shows.",
    "Last place, first heart. That's what your mom would say.",
    "The bottom of the barrel. Warm down there?",
    "You lost so hard, physics called in sick.",
    "Wooden spoon. Framed. Signed. Terrible.",
    "Dead last, {flirtGuyName}. I'm not surprised. I'm just here.",
    "The very bottom. It's a whole aesthetic.",
    "You brought a butter knife to a bazooka fight. Then you dropped the knife.",
    "Somebody had to eat dirt. Enjoy the serving.",
  ],
  goose_egg: [
    "Zero points. Zero effort. Zero shame. Zero everything.",
    "A perfect goose egg. Round. Clean. Sad.",
    "Nothing on the board. Not even a pity point.",
    "Zero. In every sense. Numerically, emotionally, spiritually.",
    "You went scoreless, {flirtGuyName}. And loud about it. Impressive.",
    "Zero. That's a choice.",
    "Big fat donut. Enjoy the calories.",
    "Absolute zero. Physically impossible to score less. Somebody call science.",
    "Nothing. Nada. Zilch. Bupkis. Whatever nothing is called in the other twelve languages.",
    "You put in the time. Nothing came out. Life.",
    "Zero. And yet, present. That's something.",
    "A goose egg. Beautiful in its emptiness.",
  ],
  idle_interject: [
    "Silence is loud, boys. And I'm judging every second of it.",
    "Somebody buzz. Somebody guess. Somebody breathe.",
    "The dead air is doing more work than any of you.",
    "{flirtGuyName}, wake up. I know you're thinking about me but focus.",
    "The Wi-Fi's fine. The confidence isn't.",
    "You're overthinking it. You're gonna be wrong anyway.",
    "This pause is longer than my last relationship. Please.",
    "Fill the silence. Or I will. And you don't want that.",
    "Somebody make a move. My drink is warming up.",
    "The room went dead. Bring it back to life, cuties.",
    "I can hear you all thinking. It's not going well.",
    "Awkward. Beautiful. Painful. Sasha-approved.",
    "Guess something. Anything. Even something stupid. Especially something stupid.",
    "Nothing? Nobody? Not even {flirtGuyName}?",
    "Come on, boys. Show me something.",
    "The silence has weight. And it's crushing me.",
    "Somebody. Anybody. Please.",
    "Every second you waste, I like you a little less.",
    "This is worse than a bad Tinder date. And I've had a few.",
    "Buzz in. Or don't. I get paid either way.",
  ],
  random_jab: [
    "{flirtGuyName}. You've been suspiciously quiet. What are you plotting?",
    "The mysterious one over there. Show me something.",
    "Silent as a fart in yoga class. Twice as awkward.",
    "That corner is way too quiet. Suspicious behavior.",
    "You've been hiding all night. Come out and play, sugar.",
    "You there. Yes, you. Blink twice if you're actually alive.",
    "The quiet ones always cheat. Or nap. Both, probably.",
    "Somebody in this lobby is doing the bare minimum. And loud about it.",
    "Talking less than {flirtGuyName}'s last date. Sad.",
    "You've contributed less than my ex. Which is somehow impressive.",
    "You could be dead and I'd only find out at the leaderboard.",
    "The mystery player. Cute. Not helping anyone.",
    "You're playing on invisible mode. Turn it off.",
    "Silent competitor detected. Suspicious. Adorable.",
    "You've been hiding. It's not working. I see you, {flirtGuyName}.",
    "Show up louder. Sasha wants to notice you.",
    "That silence isn't strategy. It's just silence.",
    "You could contribute. Or you could keep vibing. Choose.",
    "Wallflower energy. Not sexy.",
    "You're too quiet, {flirtGuyName}. Say something ridiculous, please.",
    "Ghost mode is not a look, honey.",
    "You could show off. You choose not to. Bold.",
    "Silence. Boredom. Doom. Great combo.",
    "Say something. Even nonsense. Nonsense is fine.",
    "{flirtGuyName}, break the silence or I will. And it won't be pretty.",
  ],
};
