// Adult-mode extras. Merged into LINES_ADULT in host-persona.adult.ts.
// Same content rules as the base adult file: profanity yes, slurs no,
// no minors, no real-person targeting, nothing non-consensual.

type Moment =
  | "intro_hype"
  | "question_open"
  | "all_correct"
  | "all_wrong"
  | "split_correct"
  | "first_blood"
  | "streak_milestone"
  | "elimination"
  | "leader_changed"
  | "final_hype"
  | "credits_open"
  | "comeback"
  | "round_recap"
  | "wooden_spoon"
  | "goose_egg"
  | "idle_interject"
  | "round_transition"
  | "last_to_lock"
  | "random_jab";

export const EXTRA_LINES_ADULT: Record<Moment, string[]> = {
  intro_hype: [
    "Doors sealed. Timer armed. Assholes exposed.",
    "You paid attention in third grade? Prove it, jackass.",
    "Everyone's a genius until the buzzer starts. Then everyone's a mess.",
    "Warm up your excuses. You'll need a whole fuckin file.",
    "Confidence is a currency. Yours is counterfeit.",
    "The couch is not a study aid. Regretful fucking discovery incoming.",
    "Fresh brains, fresh bruises, fresh embarrassment.",
    "I brought questions. You brought half a personality. Uneven trade.",
    "Round zero: pretend you're smart. Round one: get exposed.",
    "Warmups are for cowards. Straight into the meat, dipshits.",
    "If you googled the topic, congratulations, still not enough. Nerd.",
    "Someone here peaks in ten seconds. Someone else never does. You know who you are.",
    "Big-brain energy or bust. Bust probable.",
    "Trivia stretches: raise eyebrows, lower expectations, drop pants — pants optional.",
    "Confidence check: how loud is that inner voice? Good, we'll fuck it up.",
    "Round one is a mirror. Some of you look bad in mirrors.",
    "You've been trained your whole life for this. Barely. Poorly.",
    "Chairs comfortable? Should be. You'll be sitting through your own funeral.",
    "Warmed up? Same. Let's cook, fuckers.",
    "Trivia laws apply. Cheating laws also apply. Barely enforced.",
    "Sharpen your instincts. Blunt your ego. Cinch your pants.",
    "Guessing is a strategy. A losing one, but you'll try it anyway.",
    "Enter humble. Leave humiliated. Consistent brand.",
    "The buzzer doesn't care about your feelings. Or your excuses.",
    "Some of you will surprise yourselves. The rest will confirm every suspicion.",
    "Big talk stage left. Small results stage right. Wet pants dead center.",
    "The lights are hot. The shame is hotter.",
  ],
  question_open: [
    "Read fast, decide faster, dipshit.",
    "Trust the first instinct. It's still bad, but faster.",
    "No second guesses. Grow a spine.",
    "Snap it up, asshole.",
    "Answer's right there. Or it isn't. Coin flip.",
    "Clock's judging you. So am I.",
    "Decide already, sweaty.",
    "This one's mean. Like me.",
    "Commit or die. Metaphorically. Mostly.",
    "Look sharp. Or look stupid.",
    "Fucking move.",
    "Ticking. Loudly.",
    "Locked in? Or locked up?",
    "Answer looks close. Or it looks like a trap.",
    "Confidence check. Fail.",
    "Bet on yourself. Bad bet.",
    "One shot, jackass.",
    "Quick brain, please. Yours specifically.",
    "Wake the fuck up.",
    "Snap decision, dipshit.",
    "Read carefully. Or don't. I love watching this.",
    "Feel it. Or fake it.",
    "Timer moves. You should too, asshole.",
    "Question hot. Brain lukewarm.",
  ],
  all_correct: [
    "Unified genius. Suspicious as hell.",
    "Everyone's right. The category owes me a beer.",
    "Clean board. Boring board. Cheater board.",
    "Group won. Individually still nobodies.",
    "Total sweep. Feels wrong. Feels rigged.",
    "Perfect room. Imperfect writer. My bad.",
    "You all cheated. Nobody's denying it.",
    "Consensus achieved. Trivia weeps into its beer.",
    "Every tile lit. Nothing spicy.",
    "Universal correctness. Report to HR.",
    "Sweep. Suspicious. Filed. Dismissed.",
    "Full board. Zero drama. Boo.",
    "Group hit. Group boring.",
    "Everyone right. Nobody special.",
    "Sweep noted. Difficulty going up, fuckheads.",
    "You all know this. Cute.",
    "Perfect. Predictable. Painful.",
    "Room clean. Ego filthy.",
    "Universal W. Universally boring.",
    "Everyone got it. Genuinely alarming.",
  ],
  all_wrong: [
    "Room-wide whiff. Historic.",
    "Zero correct. Perfectly, beautifully wrong.",
    "Full plate of failure. Chef's fuckin kiss.",
    "Group L. Framed and hung over the toilet.",
    "Nobody? Really? Not one asshole?",
    "Wrong across the board. Consistent, at least.",
    "Every tile wrong. Almost artful. Almost.",
    "Room went for chaos. Chaos delivered, ass first.",
    "Perfect zero. Frame it. Tattoo it.",
    "You collectively agreed to be wrong. Bold move.",
    "Nothing correct. Nothing salvageable. Nothing sacred.",
    "Zero out of many. Poetic. Painful. Poetic and painful.",
    "You all guessed. All wrong. All embarrassed.",
    "Consensus wrongness. Impressive. Depressing.",
    "Room brain: closed for renovations.",
    "Total whiff. Sponsor me.",
    "Full room of nope.",
    "Combined intelligence: negative. Combined confidence: still peak.",
    "That question won. Handily.",
    "Question one. Room zero. Bar tab: rising.",
  ],
  split_correct: [
    "Room split. Standings shift. Egos wobble.",
    "Half brains. Half prayers. Zero shame.",
    "Sharp and shaky both showed up. Both hydrated.",
    "Some knew. Some winged it. Some are still typing.",
    "Split verdict. Sorted, painfully.",
    "Divided room. Delighted host.",
    "Some correct, some coping, some crying.",
    "Split lines drawn. In beer.",
    "Sorted the sharp from the sheepish. Rude sort.",
    "Half a win. Half a plea. Whole embarrassment.",
    "Split decision. Fair enough. Barely.",
    "Some right. Some regretful. Some rebooting.",
    "Room fractured. Politely. Damply.",
    "Sorted mid-flight. Nobody strapped in.",
    "Half genius. Half improv. All chaos.",
    "Split neatly. Painfully. Publicly.",
    "Two rooms in one. Both loud.",
    "Sorted. Filed. Judged. Roasted.",
    "Some ate. Some fumbled. Some fondled the wrong button.",
    "Split confirms rankings. Sorry, cellar dweller.",
  ],
  first_blood: [
    "Straight to the button. No thinking. Zero.",
    "First to the trigger. First to the throne. First to be hated.",
    "Someone rehearsed this. Weird flex.",
    "Snap answer. Snap correct. Snap ego.",
    "First blood, drawn quick. Drawn cocky.",
    "Fast hands. Right mind. Rude combo.",
    "Speed plus knowing. Fucking illegal.",
    "First and correct. Rude and ridiculous.",
    "Someone's caffeinated and educated. Nightmare.",
    "Reflex genius spotted. Restrain them.",
    "Locked before the rest read. Insufferable.",
    "That was quick. Correctly, insultingly quick.",
    "First across. Cocky landing.",
    "Straight in, no hesitation, no dignity for the rest.",
    "Trigger discipline: zero. Accuracy: unfair. Vibe: insufferable.",
    "Fastest brain in the room. Loudest too, probably.",
    "First out the gate. First to gloat. First to get punched.",
    "That was surgical. And a little horny.",
    "First to lock. First to smirk. First to be blocked.",
    "Sniped it clean. Rude. Deserved.",
  ],
  streak_milestone: [
    "Streak alive and fuckin mean.",
    "Heater sustained. Concerning.",
    "This one's on rails and drunk on speed.",
    "Combo climbing. Cocky climbing.",
    "Streak: alarming. Room: crying.",
    "Cooking hot. Cooking clean. Cooking crimes.",
    "Streak: professionally rude.",
    "On a run. Insufferable run.",
    "Streak count says something. It says: get out of the way.",
    "Streak stat: threatening. Streak vibe: swaggering.",
    "Locked-in mode: engaged. Chastity belt: also engaged.",
    "Streaking with confidence. And clothes. Barely.",
    "Combo says get the fuck out of the way.",
    "Streak alarm sounding. Fire marshal notified.",
    "Heat check passed with a fuckin swagger.",
    "Streak status: dangerous. Ego status: unhinged.",
    "Somebody found the flow. Rude of them.",
    "Streak: impolite.",
    "Combo unbroken. Room shaken. Pants soiled.",
    "Streak growing. Room shrinking. Chairs squeaking.",
  ],
  elimination: [
    "Dropped, tagged, filed, forgotten.",
    "Off the tile. Onto reflection. Onto therapy.",
    "Wrong click. Right regret. Small brain.",
    "Off. Cold. Filed. Fucked.",
    "That's an out, buttercup.",
    "Tapped the wrong lane. Big talent.",
    "Dropped hard. Landed loud. Bruised ego.",
    "Off the board. Onto the couch. Onto the beer.",
    "That answer lied to you. So did your confidence.",
    "Wrong tile. Right pain.",
    "Off the tour. Off the trip. Off the brand.",
    "Trapdoor engaged. Screaming optional.",
    "Went for it. Missed. Spectacularly.",
    "Wrong. Loud. Filed. Rejected.",
    "Big swing. Big miss. Big yikes.",
    "Off the board with style. Style points don't count.",
    "Confident wrongness. Loud, ugly farewell.",
    "That was courageous. And stupid. Mostly stupid.",
    "Off. Done. Sorted. Sad.",
    "Dropped. Applause is optional. Silence preferred.",
  ],
  leader_changed: [
    "New top. Old grudges. Fresh hate.",
    "Board flipped. Faces flipped. Chairs flipped.",
    "New name up top. Adjust or die.",
    "Coup logged. Peaceful. Petty.",
    "Fresh number one. Same shit.",
    "Top slot rotated. Rudely.",
    "Reigning champ down a step. And a peg.",
    "Board reshuffled. Bar tab too.",
    "New face on the marquee. Old face fuming.",
    "Old king benched. Bawling, probably.",
    "Sneaky climb. Loud landing.",
    "Top spot changed hands. Bloodlessly. Barely.",
    "Number one is a new one. Prepare the crown. And the noose.",
    "Leaderboard has a new dictator.",
    "Standing swap. Ego swap. Chair swap.",
    "Fresh face on top. Fresh fear below.",
    "Board updated. Egos updated. Beers ordered.",
    "Top spot: under new fuckin management.",
    "Leader dethroned. Quickly. Publicly.",
    "Coup complete. Bloodless. Beerless, probably not.",
  ],
  final_hype: [
    "Final question. Final regret. Final erection of stress.",
    "Wager brave. Cry proud. Drink after.",
    "One left. Make it huge. Make it dumb.",
    "This is the shot. Or the shot in the ass.",
    "Big swing time, cowards.",
    "Last drop. Best fuckin answer.",
    "One question. All chips. All pants.",
    "Wager it all or wager nothing. Both are personalities. Both are stupid.",
    "This is the one they'll roast you about at your wedding.",
    "End boss active. Bring healing potions.",
    "Final call. Big or bust. Or both.",
    "One question. Whole show. Full pants.",
    "Do the brave thing. Or the stupid thing. Same thing.",
    "Last swing. Aim true. Or don't. Fuck it.",
    "Final drop. Final answer. Final chance to not embarrass yourself.",
    "Bet everything. Or bet dignity. Both go on the tab.",
    "One shot. Loud shot. Sloppy shot.",
    "Final decision. Final memory. Final beer.",
    "Big finish incoming. Bigger regret waiting.",
    "This one lasts forever. Or until next Tuesday. Whichever.",
  ],
  credits_open: [
    "Show shipped. Egos itemized. Beers tabbed.",
    "That's a fuckin wrap. Truly.",
    "Cameras cool. Trophies warm. Toilets busy.",
    "House lights up. Pants down. Kidding. Mostly.",
    "Curtain, final. Applause optional.",
    "Trivia banked. Regrets filed. Bar open.",
    "Roll credits. Roll shoulders. Roll a joint.",
    "Show's done. Drive safe. Argue gently. Get home.",
    "That was that. Filed under: hilarious.",
    "Curtain down. Group chat up.",
    "Show closed. Debates open. Beers ordered.",
    "Names roll. Memories linger. Livers regret.",
    "That's the whole fuckin game.",
    "Trophy handed. Egos returned. Some slightly worn.",
    "Show wrapped. Refunds denied. Regrets encouraged.",
    "Show over. Argue gently. Fight fair. Kiss whoever's left.",
    "That's a full fuckin show.",
    "Cameras off. Feelings on. Pants: whereabouts unknown.",
    "Rolling names. Rolling eyes. Rolling out.",
    "That's the whole thing. Now get out.",
  ],
  comeback: [
    "Comeback confirmed. Rude comeback.",
    "Off the mat. Onto the podium. Onto everyone's nerves.",
    "Sneak riser spotted. Restrain them.",
    "Climb noticed. Threat rising. Sirens optional.",
    "Underdog waking up. About fuckin time.",
    "Basement dweller ascending. Bring a headlamp.",
    "Sleeper woke. Grumpy.",
    "Recovery in progress. So is heartburn.",
    "Back in the mix. Back in the shit.",
    "Climbing rudely. Rudely fast.",
    "Late bloomer, big fuckin bloom.",
    "Quiet climb, loud impact. Broken chairs.",
    "Comeback engaged. Bar tab too.",
    "Rejoined the fight. Sweaty.",
    "Off the floor, onto the board. Impolitely.",
    "Climb ongoing. Sirens strongly considered.",
  ],
  round_recap: [
    "Round burned. Onward, dickheads.",
    "Round shelved. Grudges kept.",
    "Round filed. Boots relaced. Beers refilled.",
    "Round done. Next.",
    "Round done. Regroup. Rehydrate.",
    "Round closed. Wounds counted. Beers ordered.",
    "Round processed. Ego pending.",
    "Round wrapped. Bruises noted.",
    "Round complete. Report submitted.",
    "Round tallied. Onward.",
    "Round tucked in. Kissed goodnight.",
    "Round complete. Deep breath. Wipe your brow.",
    "Round shipped. Next round loading. Beers refilling.",
    "Round packaged. Sent. Rejected.",
    "Round put to bed. Grumpily.",
  ],
  wooden_spoon: [
    "Wooden spoon polished. And handed to you.",
    "Basement rented. Long fuckin lease.",
    "Bottom of the pile. Cozy? Should be, you live there now.",
    "Anchor position claimed. Loudly.",
    "Last, but loud.",
    "Floor is yours. Try to keep it clean.",
    "Anchor of the round. Heavier than expected.",
    "Bottom slot booked. VIP treatment.",
    "Cellar dweller crowned. Congrats?",
    "Wooden spoon issued. Signed. Framed.",
    "Room's caboose. Toot toot.",
    "Basement king. Long may they reign, badly.",
    "Bottom of the standings, top of the excuses.",
    "The floor called. You answered. Loudly.",
  ],
  goose_egg: [
    "Big zero. Loud zero.",
    "Round score: pure fuckin zen.",
    "Donut delivered. Sprinkles of shame.",
    "Nothing scored. Everything felt.",
    "Zero, but committed. Almost admirable.",
    "Perfect nothing.",
    "Donut framed. Hung.",
    "Round score: negative vibes.",
    "Zero points, big fuckin presence.",
    "Empty stat, full personality.",
    "Round total: dignity only. Barely.",
    "Zero. With flair. With flourish. With farts.",
  ],
  idle_interject: [
    "Any fuckin second now.",
    "The silence is doing all the work.",
    "I'll keep waiting. Loudly. Petulantly.",
    "Real dramatic pause, this. And a real awkward one.",
    "Take your time. Or don't. I do not fucking care.",
    "Standby engaged. Complaints incoming.",
    "Holding. Loudly. Painfully.",
    "Dead air continues. Bar sales rise.",
    "Time is passing. Rudely.",
    "Awkward beats. On beat. Off pants.",
    "I'll wait. My contract says so. My patience does not.",
    "Silence noted. Judged. Filed.",
    "Any thoughts? Anyone? Bueller?",
    "This pause is professional. This host is not.",
    "I've stopped aging. Convenient. Concerning.",
    "Buffering hearts and minds. And bladders.",
    "Just vibes. Just standing. Just seething.",
    "Take a breath. Ok, now fucking go.",
    "Longest pause on record. Getting a plaque made.",
    "Timer says: soon. My patience says: fuck this.",
  ],
  round_transition: [
    "Round shifts. Egos jitter. Bladders too.",
    "Round flips. Brains adjust. Belts loosen.",
    "Round change. New wounds. Old grudges.",
    "Round rolls. Onward, meatheads.",
    "Round moved. Chairs shifted. Bar visited.",
    "Round pivots. Room panics.",
    "Round advances. So does danger.",
    "Round transitions. Nerves too. Beer too.",
    "Round flip. Deep breath. Deeper drink.",
    "Round hands off. Sweaty handshake.",
    "New round. New mistakes. Same idiots.",
    "Round change. Same show. Same shitshow.",
    "New chapter. Same book. Bigger typos.",
    "Round shifts, drama holds, pants: unknown.",
    "Round change. Standings breathe. Egos wheeze.",
  ],
  last_to_lock: [
    "Late lock. Legal lock. Suspicious lock.",
    "Squeaked in. Sweatily.",
    "Last across. Barely. Bravely.",
    "Right on the wire. Right on the edge.",
    "Late but locked. Points count. Barely.",
    "By a whisker. Or a nose hair.",
    "Buzzer kiss. Legal. Uncomfortable.",
    "Late lock, clean. Just clean.",
    "Slid in on the horn. Slid in dirty.",
    "Cutting it thin. Living dangerously. Peeing slightly.",
    "Waited. Then locked. Nice pulse. Weird timing.",
    "Down to the wire and past. Cocky.",
  ],
  random_jab: [
    "Still here. Barely. Silently.",
    "Silent competitor spotted. Suspicious.",
    "Quiet corner detected. Plotting corner.",
    "Sneaky player mode. Sneaky pants mode.",
    "Lurking. Judging. Vibing. Farting.",
    "Present, if not accounted for.",
    "Ghost in the room. Horny ghost.",
    "Silent scorer, silent story, silent-but-deadly.",
    "Background character noted. Filed.",
    "Vibes strong. Score TBD. Pants TBD.",
    "Wallflower with intent. Slightly damp intent.",
    "Not saying much. Not doing much. Not scoring much.",
    "Lurking with intent. Weird intent.",
  ],
};
