/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewQuestionRouteImport } from './routes/preview-question'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HostRouteImport } from './routes/host'
import { Route as HRouteImport } from './routes/h'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AudienceRouteImport } from './routes/audience'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsStreamerRouteImport } from './routes/settings.streamer'
import { Route as ResultsRoomIdRouteImport } from './routes/results.$roomId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalContactRouteImport } from './routes/legal.contact'
import { Route as AuthenticatedAdminSoundsRouteImport } from './routes/_authenticated/admin-sounds'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin-questions'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksQuestionQualityAlertRouteImport } from './routes/api/public/hooks/question-quality-alert'
import { Route as ApiPublicHooksCleanupAvatarsRouteImport } from './routes/api/public/hooks/cleanup-avatars'

const PreviewQuestionRoute = PreviewQuestionRouteImport.update({
  id: '/preview-question',
  path: '/preview-question',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HRoute = HRouteImport.update({
  id: '/h',
  path: '/h',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienceRoute = AudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsStreamerRoute = SettingsStreamerRouteImport.update({
  id: '/settings/streamer',
  path: '/settings/streamer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoomIdRoute = ResultsRoomIdRouteImport.update({
  id: '/results/$roomId',
  path: '/results/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalContactRoute = LegalContactRouteImport.update({
  id: '/legal/contact',
  path: '/legal/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSoundsRoute =
  AuthenticatedAdminSoundsRouteImport.update({
    id: '/admin-sounds',
    path: '/admin-sounds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin-questions',
    path: '/admin-questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksQuestionQualityAlertRoute =
  ApiPublicHooksQuestionQualityAlertRouteImport.update({
    id: '/api/public/hooks/question-quality-alert',
    path: '/api/public/hooks/question-quality-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupAvatarsRoute =
  ApiPublicHooksCleanupAvatarsRouteImport.update({
    id: '/api/public/hooks/cleanup-avatars',
    path: '/api/public/hooks/cleanup-avatars',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/dev': typeof DevRoute
  '/h': typeof HRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin-sounds': typeof AuthenticatedAdminSoundsRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/results/$roomId': typeof ResultsRoomIdRoute
  '/settings/streamer': typeof SettingsStreamerRoute
  '/api/public/hooks/cleanup-avatars': typeof ApiPublicHooksCleanupAvatarsRoute
  '/api/public/hooks/question-quality-alert': typeof ApiPublicHooksQuestionQualityAlertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audience': typeof AudienceRoute
  '/dev': typeof DevRoute
  '/h': typeof HRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin-sounds': typeof AuthenticatedAdminSoundsRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/results/$roomId': typeof ResultsRoomIdRoute
  '/settings/streamer': typeof SettingsStreamerRoute
  '/api/public/hooks/cleanup-avatars': typeof ApiPublicHooksCleanupAvatarsRoute
  '/api/public/hooks/question-quality-alert': typeof ApiPublicHooksQuestionQualityAlertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/audience': typeof AudienceRoute
  '/dev': typeof DevRoute
  '/h': typeof HRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin-sounds': typeof AuthenticatedAdminSoundsRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/results/$roomId': typeof ResultsRoomIdRoute
  '/settings/streamer': typeof SettingsStreamerRoute
  '/api/public/hooks/cleanup-avatars': typeof ApiPublicHooksCleanupAvatarsRoute
  '/api/public/hooks/question-quality-alert': typeof ApiPublicHooksQuestionQualityAlertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audience'
    | '/dev'
    | '/h'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/admin'
    | '/admin-questions'
    | '/admin-sounds'
    | '/legal/contact'
    | '/legal/privacy'
    | '/legal/terms'
    | '/results/$roomId'
    | '/settings/streamer'
    | '/api/public/hooks/cleanup-avatars'
    | '/api/public/hooks/question-quality-alert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audience'
    | '/dev'
    | '/h'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/admin'
    | '/admin-questions'
    | '/admin-sounds'
    | '/legal/contact'
    | '/legal/privacy'
    | '/legal/terms'
    | '/results/$roomId'
    | '/settings/streamer'
    | '/api/public/hooks/cleanup-avatars'
    | '/api/public/hooks/question-quality-alert'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/audience'
    | '/dev'
    | '/h'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/_authenticated/admin'
    | '/_authenticated/admin-questions'
    | '/_authenticated/admin-sounds'
    | '/legal/contact'
    | '/legal/privacy'
    | '/legal/terms'
    | '/results/$roomId'
    | '/settings/streamer'
    | '/api/public/hooks/cleanup-avatars'
    | '/api/public/hooks/question-quality-alert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AudienceRoute: typeof AudienceRoute
  DevRoute: typeof DevRoute
  HRoute: typeof HRoute
  HostRoute: typeof HostRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PreviewQuestionRoute: typeof PreviewQuestionRoute
  LegalContactRoute: typeof LegalContactRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ResultsRoomIdRoute: typeof ResultsRoomIdRoute
  SettingsStreamerRoute: typeof SettingsStreamerRoute
  ApiPublicHooksCleanupAvatarsRoute: typeof ApiPublicHooksCleanupAvatarsRoute
  ApiPublicHooksQuestionQualityAlertRoute: typeof ApiPublicHooksQuestionQualityAlertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview-question': {
      id: '/preview-question'
      path: '/preview-question'
      fullPath: '/preview-question'
      preLoaderRoute: typeof PreviewQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h': {
      id: '/h'
      path: '/h'
      fullPath: '/h'
      preLoaderRoute: typeof HRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audience': {
      id: '/audience'
      path: '/audience'
      fullPath: '/audience'
      preLoaderRoute: typeof AudienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/streamer': {
      id: '/settings/streamer'
      path: '/settings/streamer'
      fullPath: '/settings/streamer'
      preLoaderRoute: typeof SettingsStreamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$roomId': {
      id: '/results/$roomId'
      path: '/results/$roomId'
      fullPath: '/results/$roomId'
      preLoaderRoute: typeof ResultsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/contact': {
      id: '/legal/contact'
      path: '/legal/contact'
      fullPath: '/legal/contact'
      preLoaderRoute: typeof LegalContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-sounds': {
      id: '/_authenticated/admin-sounds'
      path: '/admin-sounds'
      fullPath: '/admin-sounds'
      preLoaderRoute: typeof AuthenticatedAdminSoundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-questions': {
      id: '/_authenticated/admin-questions'
      path: '/admin-questions'
      fullPath: '/admin-questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/question-quality-alert': {
      id: '/api/public/hooks/question-quality-alert'
      path: '/api/public/hooks/question-quality-alert'
      fullPath: '/api/public/hooks/question-quality-alert'
      preLoaderRoute: typeof ApiPublicHooksQuestionQualityAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-avatars': {
      id: '/api/public/hooks/cleanup-avatars'
      path: '/api/public/hooks/cleanup-avatars'
      fullPath: '/api/public/hooks/cleanup-avatars'
      preLoaderRoute: typeof ApiPublicHooksCleanupAvatarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminSoundsRoute: typeof AuthenticatedAdminSoundsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminSoundsRoute: AuthenticatedAdminSoundsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AudienceRoute: AudienceRoute,
  DevRoute: DevRoute,
  HRoute: HRoute,
  HostRoute: HostRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PreviewQuestionRoute: PreviewQuestionRoute,
  LegalContactRoute: LegalContactRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ResultsRoomIdRoute: ResultsRoomIdRoute,
  SettingsStreamerRoute: SettingsStreamerRoute,
  ApiPublicHooksCleanupAvatarsRoute: ApiPublicHooksCleanupAvatarsRoute,
  ApiPublicHooksQuestionQualityAlertRoute:
    ApiPublicHooksQuestionQualityAlertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
