/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewQuestionRouteImport } from './routes/preview-question'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HostRouteImport } from './routes/host'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminSoundsRouteImport } from './routes/_authenticated/admin.sounds'

const PreviewQuestionRoute = PreviewQuestionRouteImport.update({
  id: '/preview-question',
  path: '/preview-question',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSoundsRoute =
  AuthenticatedAdminSoundsRouteImport.update({
    id: '/sounds',
    path: '/sounds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/sounds': typeof AuthenticatedAdminSoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/sounds': typeof AuthenticatedAdminSoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dev': typeof DevRoute
  '/host': typeof HostRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/preview-question': typeof PreviewQuestionRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/sounds': typeof AuthenticatedAdminSoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/admin'
    | '/admin/sounds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/admin'
    | '/admin/sounds'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dev'
    | '/host'
    | '/join'
    | '/login'
    | '/play'
    | '/preview-question'
    | '/_authenticated/admin'
    | '/_authenticated/admin/sounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevRoute: typeof DevRoute
  HostRoute: typeof HostRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  PreviewQuestionRoute: typeof PreviewQuestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview-question': {
      id: '/preview-question'
      path: '/preview-question'
      fullPath: '/preview-question'
      preLoaderRoute: typeof PreviewQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sounds': {
      id: '/_authenticated/admin/sounds'
      path: '/sounds'
      fullPath: '/admin/sounds'
      preLoaderRoute: typeof AuthenticatedAdminSoundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSoundsRoute: typeof AuthenticatedAdminSoundsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSoundsRoute: AuthenticatedAdminSoundsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevRoute: DevRoute,
  HostRoute: HostRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  PreviewQuestionRoute: PreviewQuestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
