
INSERT INTO public.questions (category, question_text, correct_answer, wrong_1, wrong_2, wrong_3, is_premium) VALUES
-- Music
('Music','Which band released the album "Abbey Road"?','The Beatles','The Rolling Stones','Led Zeppelin','The Who',false),
('Music','Who is known as the "Queen of Pop"?','Madonna','Beyoncé','Whitney Houston','Mariah Carey',false),
('Music','What instrument does Yo-Yo Ma play?','Cello','Violin','Piano','Flute',false),
('Music','Which artist sang "Rolling in the Deep"?','Adele','Sia','Amy Winehouse','Duffy',false),
('Music','How many strings does a standard guitar have?','6','4','7','8',false),
('Music','Who produced "Thriller"?','Quincy Jones','Dr. Dre','Rick Rubin','George Martin',false),
('Music','Which band performed "Bohemian Rhapsody"?','Queen','The Eagles','Pink Floyd','Genesis',false),
('Music','What genre is Bob Marley most associated with?','Reggae','Ska','Calypso','Jazz',false),
('Music','Which rapper released "good kid, m.A.A.d city"?','Kendrick Lamar','J. Cole','Drake','Jay-Z',false),
('Music','Who composed "The Four Seasons"?','Antonio Vivaldi','Mozart','Beethoven','Bach',false),
('Music','Which singer''s real name is Stefani Germanotta?','Lady Gaga','Katy Perry','Pink','Rihanna',false),
('Music','What city is Motown Records from?','Detroit','New York','Memphis','Chicago',false),
('Music','Which Beatle was assassinated in 1980?','John Lennon','Paul McCartney','George Harrison','Ringo Starr',false),
('Music','Who sang "Like a Prayer"?','Madonna','Cher','Cyndi Lauper','Whitney Houston',false),
('Music','What does DJ stand for?','Disc Jockey','Disco Jam','Digital Jukebox','Dance Jockey',false),
('Music','Which K-pop group sang "Dynamite"?','BTS','BLACKPINK','TWICE','EXO',false),
('Music','Who is the lead singer of U2?','Bono','The Edge','Adam Clayton','Larry Mullen',false),
('Music','What is Taylor Swift''s re-recorded album suffix?','(Taylor''s Version)','(Re-Recorded)','(Original)','(Vault)',false),
('Music','Which instrument has 88 keys?','Piano','Harpsichord','Accordion','Organ',false),
('Music','Who sang "Purple Rain"?','Prince','Michael Jackson','David Bowie','Lenny Kravitz',false),

-- Movies
('Movies','Who directed "Jurassic Park"?','Steven Spielberg','James Cameron','George Lucas','Ridley Scott',false),
('Movies','What year did "Titanic" release?','1997','1995','1998','1999',false),
('Movies','Who played the Joker in "The Dark Knight"?','Heath Ledger','Jack Nicholson','Jared Leto','Joaquin Phoenix',false),
('Movies','What is the highest-grossing film of all time?','Avatar','Avengers: Endgame','Titanic','Star Wars: The Force Awakens',false),
('Movies','Which film features the quote "I''ll be back"?','The Terminator','Predator','Total Recall','Commando',false),
('Movies','Who directed "Pulp Fiction"?','Quentin Tarantino','Martin Scorsese','Coen Brothers','David Fincher',false),
('Movies','In "The Matrix", what color pill does Neo take?','Red','Blue','Green','Yellow',false),
('Movies','Which Pixar film features a rat who cooks?','Ratatouille','Bee Movie','Antz','A Bug''s Life',false),
('Movies','Who played Forrest Gump?','Tom Hanks','Tom Cruise','Kevin Costner','Bill Murray',false),
('Movies','What''s the name of the wizarding school in Harry Potter?','Hogwarts','Durmstrang','Beauxbatons','Ilvermorny',false),
('Movies','Who composed the "Star Wars" score?','John Williams','Hans Zimmer','Danny Elfman','James Horner',false),
('Movies','Which film won Best Picture in 2020?','Parasite','1917','Joker','Once Upon a Time in Hollywood',false),
('Movies','Who played Jack Sparrow?','Johnny Depp','Orlando Bloom','Geoffrey Rush','Brad Pitt',false),
('Movies','What is the name of Andy''s cowboy toy in "Toy Story"?','Woody','Buzz','Rex','Slinky',false),
('Movies','Which actor starred as Iron Man?','Robert Downey Jr.','Chris Evans','Mark Ruffalo','Chris Hemsworth',false),
('Movies','Who directed "Inception"?','Christopher Nolan','James Cameron','Denis Villeneuve','Ridley Scott',false),
('Movies','Which film features dancing dinosaurs in tutus?','Fantasia','Bambi','Dumbo','Pinocchio',false),
('Movies','Who voices Shrek?','Mike Myers','Eddie Murphy','Antonio Banderas','John Lithgow',false),
('Movies','What''s the longest-running James Bond actor?','Roger Moore','Sean Connery','Daniel Craig','Pierce Brosnan',false),
('Movies','Which film opens with "A long time ago in a galaxy far, far away..."?','Star Wars','Star Trek','Dune','Guardians of the Galaxy',false),

-- General Knowledge
('General Knowledge','What is the capital of Australia?','Canberra','Sydney','Melbourne','Perth',false),
('General Knowledge','How many continents are there?','7','5','6','8',false),
('General Knowledge','What is the chemical symbol for gold?','Au','Ag','Gd','Go',false),
('General Knowledge','How many sides does a hexagon have?','6','5','7','8',false),
('General Knowledge','What is the largest mammal?','Blue Whale','African Elephant','Giraffe','Polar Bear',false),
('General Knowledge','Which planet is closest to the sun?','Mercury','Venus','Earth','Mars',false),
('General Knowledge','What language has the most native speakers?','Mandarin Chinese','English','Spanish','Hindi',false),
('General Knowledge','How many bones in the adult human body?','206','201','220','195',false),
('General Knowledge','What''s the smallest country in the world?','Vatican City','Monaco','San Marino','Liechtenstein',false),
('General Knowledge','Who painted the Mona Lisa?','Leonardo da Vinci','Michelangelo','Raphael','Donatello',false),
('General Knowledge','What gas do plants breathe in?','Carbon Dioxide','Oxygen','Nitrogen','Hydrogen',false),
('General Knowledge','What''s the currency of Japan?','Yen','Won','Yuan','Ringgit',false),
('General Knowledge','How many colors in a rainbow?','7','6','8','5',false),
('General Knowledge','What''s the hardest natural substance?','Diamond','Steel','Quartz','Granite',false),
('General Knowledge','Which ocean is the largest?','Pacific','Atlantic','Indian','Arctic',false),
('General Knowledge','How many minutes in a day?','1440','1240','1480','1200',false),
('General Knowledge','What''s the boiling point of water in Celsius?','100','90','110','80',false),
('General Knowledge','Who wrote "Romeo and Juliet"?','Shakespeare','Dickens','Austen','Chaucer',false),
('General Knowledge','How many teeth does an adult human have?','32','28','30','34',false),
('General Knowledge','What''s the tallest mountain on Earth?','Mount Everest','K2','Kangchenjunga','Lhotse',false),

-- Sports
('Sports','How many players on a soccer team on the field?','11','10','12','9',false),
('Sports','Which country won the 2022 FIFA World Cup?','Argentina','France','Brazil','Germany',false),
('Sports','In which sport is "love" a score?','Tennis','Cricket','Badminton','Squash',false),
('Sports','How many holes in a standard round of golf?','18','9','12','24',false),
('Sports','Who has the most NBA championships as a player?','Bill Russell','Michael Jordan','LeBron James','Kobe Bryant',false),
('Sports','What sport is Wimbledon associated with?','Tennis','Cricket','Rugby','Golf',false),
('Sports','How long is an Olympic marathon (km)?','42.195','40','45','38',false),
('Sports','Which boxer was called "The Greatest"?','Muhammad Ali','Mike Tyson','Joe Frazier','George Foreman',false),
('Sports','How many points is a touchdown worth?','6','7','3','5',false),
('Sports','Where were the 2016 Summer Olympics held?','Rio de Janeiro','London','Tokyo','Beijing',false),
('Sports','Which country invented table tennis?','England','China','Japan','Germany',false),
('Sports','How many rings on the Olympic flag?','5','4','6','7',false),
('Sports','Who holds the men''s 100m world record?','Usain Bolt','Tyson Gay','Yohan Blake','Justin Gatlin',false),
('Sports','In baseball, how many strikes is an out?','3','2','4','5',false),
('Sports','What''s the diameter of a basketball hoop (inches)?','18','16','20','22',false),
('Sports','Which F1 driver has the most world titles (tied)?','Lewis Hamilton','Sebastian Vettel','Ayrton Senna','Alain Prost',false),
('Sports','How many players on an ice hockey team on the ice?','6','5','7','8',false),
('Sports','What''s a perfect score in bowling?','300','200','250','350',false),
('Sports','Which sport uses a shuttlecock?','Badminton','Tennis','Squash','Table Tennis',false),
('Sports','Who won the 2023 NBA MVP?','Joel Embiid','Nikola Jokić','Giannis Antetokounmpo','Jayson Tatum',false),

-- History
('History','In what year did WWII end?','1945','1944','1946','1943',false),
('History','Who was the first US president?','George Washington','Thomas Jefferson','John Adams','Benjamin Franklin',false),
('History','The Great Wall is in which country?','China','Mongolia','Japan','Korea',false),
('History','Who was the first woman to win a Nobel Prize?','Marie Curie','Rosalind Franklin','Ada Lovelace','Florence Nightingale',false),
('History','Which empire was led by Julius Caesar?','Roman','Greek','Egyptian','Persian',false),
('History','When did the Berlin Wall fall?','1989','1991','1987','1985',false),
('History','Who painted the Sistine Chapel ceiling?','Michelangelo','Leonardo da Vinci','Raphael','Botticelli',false),
('History','Which civilization built Machu Picchu?','Inca','Aztec','Maya','Olmec',false),
('History','In what year did the Titanic sink?','1912','1910','1915','1908',false),
('History','Who was the British PM during most of WWII?','Winston Churchill','Neville Chamberlain','Clement Attlee','Anthony Eden',false),
('History','Which country gifted the Statue of Liberty to the US?','France','England','Spain','Italy',false),
('History','When did humans first land on the Moon?','1969','1965','1971','1972',false),
('History','Who wrote "The Communist Manifesto" with Engels?','Karl Marx','Lenin','Stalin','Trotsky',false),
('History','What ancient wonder was in Alexandria?','The Lighthouse','The Hanging Gardens','The Colossus','The Pyramids',false),
('History','Which queen ruled the UK for 70+ years?','Elizabeth II','Victoria','Elizabeth I','Mary I',false),
('History','What year did the USSR dissolve?','1991','1989','1993','1990',false),
('History','Who discovered penicillin?','Alexander Fleming','Louis Pasteur','Joseph Lister','Edward Jenner',false),
('History','Which war was fought between the North and South US?','American Civil War','Revolutionary War','War of 1812','Spanish-American War',false),
('History','Who was the longest-serving US president?','Franklin D. Roosevelt','Abraham Lincoln','Ronald Reagan','Bill Clinton',false),
('History','Which pharaoh''s tomb was discovered in 1922?','Tutankhamun','Ramses II','Cleopatra','Akhenaten',false),

-- TV Shows
('TV Shows','Who is the main character of "Breaking Bad"?','Walter White','Jesse Pinkman','Saul Goodman','Hank Schrader',false),
('TV Shows','What''s the coffee shop in "Friends"?','Central Perk','Café Nervosa','MacLaren''s','Monk''s',false),
('TV Shows','Which show features the Iron Throne?','Game of Thrones','The Witcher','Vikings','House of the Dragon',false),
('TV Shows','In "The Office" (US), what company do they work for?','Dunder Mifflin','Initech','Vandelay','Pied Piper',false),
('TV Shows','Who plays Eleven in "Stranger Things"?','Millie Bobby Brown','Sadie Sink','Maya Hawke','Natalia Dyer',false),
('TV Shows','Which show is about Hawkins, Indiana?','Stranger Things','Riverdale','Twin Peaks','Wayward Pines',false),
('TV Shows','What is Sheldon''s catchphrase in "The Big Bang Theory"?','Bazinga','Yippee','Whammy','Kapow',false),
('TV Shows','Who hosts "The Tonight Show" since 2014?','Jimmy Fallon','Jimmy Kimmel','Stephen Colbert','Conan O''Brien',false),
('TV Shows','What''s the name of the dragon in "House of the Dragon" ridden by Rhaenyra?','Syrax','Caraxes','Vhagar','Meleys',false),
('TV Shows','Which show is set in Pawnee, Indiana?','Parks and Recreation','The Office','Community','Brooklyn Nine-Nine',false),
('TV Shows','What is the prison in "Orange Is the New Black"?','Litchfield','Shawshank','Folsom','Rikers',false),
('TV Shows','Which animated family lives in Springfield?','The Simpsons','Family Guy','American Dad','Bob''s Burgers',false),
('TV Shows','Who is the lead in "Sherlock" (BBC)?','Benedict Cumberbatch','Martin Freeman','Tom Hiddleston','Andrew Scott',false),
('TV Shows','What network aired "The Sopranos"?','HBO','Showtime','AMC','Netflix',false),
('TV Shows','What''s Ted Lasso''s sport?','Soccer','American Football','Basketball','Baseball',false),
('TV Shows','Which show features Daenerys Targaryen?','Game of Thrones','The Witcher','Outlander','Rome',false),
('TV Shows','Who created "Black Mirror"?','Charlie Brooker','Vince Gilligan','David Lynch','Russell T Davies',false),
('TV Shows','What is the name of the bar in "Cheers"?','Cheers','Moe''s','MacLaren''s','Paddy''s',false),
('TV Shows','Who plays Tony Soprano?','James Gandolfini','Robert De Niro','Joe Pesci','Ray Liotta',false),
('TV Shows','Which show follows Don Draper?','Mad Men','Better Call Saul','The Americans','Boardwalk Empire',false),

-- Geography
('Geography','What''s the longest river in the world?','Nile','Amazon','Yangtze','Mississippi',false),
('Geography','Which country has the most population?','India','China','USA','Indonesia',false),
('Geography','What''s the capital of Canada?','Ottawa','Toronto','Vancouver','Montreal',false),
('Geography','Which desert is the largest?','Antarctic','Sahara','Arabian','Gobi',false),
('Geography','What country is shaped like a boot?','Italy','Greece','Croatia','Portugal',false),
('Geography','Which African country was formerly called Abyssinia?','Ethiopia','Sudan','Kenya','Eritrea',false),
('Geography','What''s the smallest US state by area?','Rhode Island','Delaware','Connecticut','Vermont',false),
('Geography','Which mountain range runs through South America?','Andes','Rockies','Alps','Atlas',false),
('Geography','What is the deepest ocean trench?','Mariana Trench','Tonga Trench','Java Trench','Puerto Rico Trench',false),
('Geography','Which country has the most time zones?','France','Russia','USA','China',false),
('Geography','What is the capital of Brazil?','Brasília','Rio de Janeiro','São Paulo','Salvador',false),
('Geography','Which sea is between Europe and Africa?','Mediterranean','Black','Red','Caspian',false),
('Geography','What''s the largest country by area?','Russia','Canada','China','USA',false),
('Geography','Which city is known as "The Big Apple"?','New York','Chicago','Boston','Los Angeles',false),
('Geography','What''s the longest mountain range on Earth (above water)?','Andes','Himalayas','Rockies','Atlas',false),
('Geography','In which country are the Pyramids of Giza?','Egypt','Sudan','Libya','Mexico',false),
('Geography','What''s the capital of South Korea?','Seoul','Busan','Incheon','Pyongyang',false),
('Geography','Which river runs through London?','Thames','Seine','Danube','Rhine',false),
('Geography','What''s the only sea without coastlines?','Sargasso Sea','Black Sea','Dead Sea','Caspian Sea',false),
('Geography','Which country has the maple leaf flag?','Canada','Norway','Finland','New Zealand',false),

-- Science
('Science','What planet is known as the Red Planet?','Mars','Venus','Jupiter','Mercury',false),
('Science','What is H2O commonly known as?','Water','Hydrogen Peroxide','Salt','Steam',false),
('Science','What force keeps us on the ground?','Gravity','Magnetism','Friction','Inertia',false),
('Science','How many planets in our solar system?','8','9','7','10',false),
('Science','What organ pumps blood in the human body?','Heart','Liver','Lungs','Kidney',false),
('Science','What is the speed of light (km/s, approx)?','300000','150000','450000','600000',false),
('Science','Who proposed the theory of relativity?','Albert Einstein','Isaac Newton','Niels Bohr','Galileo',false),
('Science','What is the largest planet?','Jupiter','Saturn','Neptune','Earth',false),
('Science','What''s the chemical symbol for sodium?','Na','So','Sd','Sa',false),
('Science','What gas do humans exhale?','Carbon Dioxide','Oxygen','Nitrogen','Helium',false),
('Science','What''s the smallest unit of matter?','Atom','Molecule','Cell','Electron',false),
('Science','What''s the powerhouse of the cell?','Mitochondria','Nucleus','Ribosome','Golgi Apparatus',false),
('Science','How many chambers in the human heart?','4','2','3','5',false),
('Science','What''s the most abundant gas in Earth''s atmosphere?','Nitrogen','Oxygen','Carbon Dioxide','Argon',false),
('Science','What''s the study of fossils called?','Paleontology','Archaeology','Geology','Anthropology',false),
('Science','What''s the unit of electrical resistance?','Ohm','Volt','Watt','Ampere',false),
('Science','Which scientist discovered gravity from an apple?','Isaac Newton','Albert Einstein','Galileo','Stephen Hawking',false),
('Science','What''s DNA short for?','Deoxyribonucleic Acid','Dinucleic Acid','Deoxyribose Nuclear Acid','Diribose Nucleic Acid',false),
('Science','Which blood type is the universal donor?','O negative','AB positive','A positive','O positive',false),
('Science','What''s absolute zero in Celsius?','-273.15','-100','-200','-459.67',false);
